//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.19 at 07:48:00 PM CEST 
//


package essilor.integrator.adapter.domain.b2boptic;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for Bevel complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Bevel">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="type" type="{}BevelTypes"/>
 *         &lt;element name="position" maxOccurs="2" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>float">
 *                 &lt;attribute name="posType" type="{}BevelPosType" default="AUTO" />
 *                 &lt;attribute name="side" type="{}Sides" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="grooveDepth" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="grooveWidth" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Bevel", propOrder = {
    "type",
    "position",
    "grooveDepth",
    "grooveWidth"
})
public class Bevel {

    @XmlElement(required = true)
    protected BevelTypes type;
    protected List<Bevel.Position> position;
    protected Float grooveDepth;
    protected Float grooveWidth;

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link BevelTypes }
     *     
     */
    public BevelTypes getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link BevelTypes }
     *     
     */
    public void setType(BevelTypes value) {
        this.type = value;
    }

    /**
     * Gets the value of the position property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the position property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPosition().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Bevel.Position }
     * 
     * 
     */
    public List<Bevel.Position> getPosition() {
        if (position == null) {
            position = new ArrayList<Bevel.Position>();
        }
        return this.position;
    }

    /**
     * Gets the value of the grooveDepth property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getGrooveDepth() {
        return grooveDepth;
    }

    /**
     * Sets the value of the grooveDepth property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setGrooveDepth(Float value) {
        this.grooveDepth = value;
    }

    /**
     * Gets the value of the grooveWidth property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getGrooveWidth() {
        return grooveWidth;
    }

    /**
     * Sets the value of the grooveWidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setGrooveWidth(Float value) {
        this.grooveWidth = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>float">
     *       &lt;attribute name="posType" type="{}BevelPosType" default="AUTO" />
     *       &lt;attribute name="side" type="{}Sides" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Position {

        @XmlValue
        protected float value;
        @XmlAttribute(name = "posType")
        protected BevelPosType posType;
        @XmlAttribute(name = "side")
        protected Sides side;

        /**
         * Gets the value of the value property.
         * 
         */
        public float getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         */
        public void setValue(float value) {
            this.value = value;
        }

        /**
         * Gets the value of the posType property.
         * 
         * @return
         *     possible object is
         *     {@link BevelPosType }
         *     
         */
        public BevelPosType getPosType() {
            if (posType == null) {
                return BevelPosType.AUTO;
            } else {
                return posType;
            }
        }

        /**
         * Sets the value of the posType property.
         * 
         * @param value
         *     allowed object is
         *     {@link BevelPosType }
         *     
         */
        public void setPosType(BevelPosType value) {
            this.posType = value;
        }

        /**
         * Gets the value of the side property.
         * 
         * @return
         *     possible object is
         *     {@link Sides }
         *     
         */
        public Sides getSide() {
            return side;
        }

        /**
         * Sets the value of the side property.
         * 
         * @param value
         *     allowed object is
         *     {@link Sides }
         *     
         */
        public void setSide(Sides value) {
            this.side = value;
        }

    }

}
