//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.19 at 07:48:00 PM CEST 
//


package essilor.integrator.adapter.domain.b2boptic;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for Centration complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Centration">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="monocularCentrationDistance">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>float">
 *                 &lt;attribute name="reference" use="required" type="{}OCReferences" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="height">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>float">
 *                 &lt;attribute name="reference" use="required" type="{}OCReferences" />
 *                 &lt;attribute name="referenceHeight" use="required" type="{}HeightReferences" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="backVertexDistance" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="eyeRotationCenterDistance" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>float">
 *                 &lt;attribute name="reference" use="required" type="{}RCDReferences" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Centration", propOrder = {
    "monocularCentrationDistance",
    "height",
    "backVertexDistance",
    "eyeRotationCenterDistance"
})
public class Centration {

    @XmlElement(required = true)
    protected Centration.MonocularCentrationDistance monocularCentrationDistance;
    @XmlElement(required = true)
    protected Centration.Height height;
    protected Float backVertexDistance;
    protected Centration.EyeRotationCenterDistance eyeRotationCenterDistance;

    /**
     * Gets the value of the monocularCentrationDistance property.
     * 
     * @return
     *     possible object is
     *     {@link Centration.MonocularCentrationDistance }
     *     
     */
    public Centration.MonocularCentrationDistance getMonocularCentrationDistance() {
        return monocularCentrationDistance;
    }

    /**
     * Sets the value of the monocularCentrationDistance property.
     * 
     * @param value
     *     allowed object is
     *     {@link Centration.MonocularCentrationDistance }
     *     
     */
    public void setMonocularCentrationDistance(Centration.MonocularCentrationDistance value) {
        this.monocularCentrationDistance = value;
    }

    /**
     * Gets the value of the height property.
     * 
     * @return
     *     possible object is
     *     {@link Centration.Height }
     *     
     */
    public Centration.Height getHeight() {
        return height;
    }

    /**
     * Sets the value of the height property.
     * 
     * @param value
     *     allowed object is
     *     {@link Centration.Height }
     *     
     */
    public void setHeight(Centration.Height value) {
        this.height = value;
    }

    /**
     * Gets the value of the backVertexDistance property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getBackVertexDistance() {
        return backVertexDistance;
    }

    /**
     * Sets the value of the backVertexDistance property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setBackVertexDistance(Float value) {
        this.backVertexDistance = value;
    }

    /**
     * Gets the value of the eyeRotationCenterDistance property.
     * 
     * @return
     *     possible object is
     *     {@link Centration.EyeRotationCenterDistance }
     *     
     */
    public Centration.EyeRotationCenterDistance getEyeRotationCenterDistance() {
        return eyeRotationCenterDistance;
    }

    /**
     * Sets the value of the eyeRotationCenterDistance property.
     * 
     * @param value
     *     allowed object is
     *     {@link Centration.EyeRotationCenterDistance }
     *     
     */
    public void setEyeRotationCenterDistance(Centration.EyeRotationCenterDistance value) {
        this.eyeRotationCenterDistance = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>float">
     *       &lt;attribute name="reference" use="required" type="{}RCDReferences" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class EyeRotationCenterDistance {

        @XmlValue
        protected float value;
        @XmlAttribute(name = "reference", required = true)
        protected RCDReferences reference;

        /**
         * Gets the value of the value property.
         * 
         */
        public float getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         */
        public void setValue(float value) {
            this.value = value;
        }

        /**
         * Gets the value of the reference property.
         * 
         * @return
         *     possible object is
         *     {@link RCDReferences }
         *     
         */
        public RCDReferences getReference() {
            return reference;
        }

        /**
         * Sets the value of the reference property.
         * 
         * @param value
         *     allowed object is
         *     {@link RCDReferences }
         *     
         */
        public void setReference(RCDReferences value) {
            this.reference = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>float">
     *       &lt;attribute name="reference" use="required" type="{}OCReferences" />
     *       &lt;attribute name="referenceHeight" use="required" type="{}HeightReferences" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Height {

        @XmlValue
        protected float value;
        @XmlAttribute(name = "reference", required = true)
        protected OCReferences reference;
        @XmlAttribute(name = "referenceHeight", required = true)
        protected HeightReferences referenceHeight;

        /**
         * Gets the value of the value property.
         * 
         */
        public float getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         */
        public void setValue(float value) {
            this.value = value;
        }

        /**
         * Gets the value of the reference property.
         * 
         * @return
         *     possible object is
         *     {@link OCReferences }
         *     
         */
        public OCReferences getReference() {
            return reference;
        }

        /**
         * Sets the value of the reference property.
         * 
         * @param value
         *     allowed object is
         *     {@link OCReferences }
         *     
         */
        public void setReference(OCReferences value) {
            this.reference = value;
        }

        /**
         * Gets the value of the referenceHeight property.
         * 
         * @return
         *     possible object is
         *     {@link HeightReferences }
         *     
         */
        public HeightReferences getReferenceHeight() {
            return referenceHeight;
        }

        /**
         * Sets the value of the referenceHeight property.
         * 
         * @param value
         *     allowed object is
         *     {@link HeightReferences }
         *     
         */
        public void setReferenceHeight(HeightReferences value) {
            this.referenceHeight = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>float">
     *       &lt;attribute name="reference" use="required" type="{}OCReferences" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class MonocularCentrationDistance {

        @XmlValue
        protected float value;
        @XmlAttribute(name = "reference", required = true)
        protected OCReferences reference;

        /**
         * Gets the value of the value property.
         * 
         */
        public float getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         */
        public void setValue(float value) {
            this.value = value;
        }

        /**
         * Gets the value of the reference property.
         * 
         * @return
         *     possible object is
         *     {@link OCReferences }
         *     
         */
        public OCReferences getReference() {
            return reference;
        }

        /**
         * Sets the value of the reference property.
         * 
         * @param value
         *     allowed object is
         *     {@link OCReferences }
         *     
         */
        public void setReference(OCReferences value) {
            this.reference = value;
        }

    }

}
