//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.19 at 07:48:00 PM CEST 
//


package essilor.integrator.adapter.domain.b2boptic;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Curve complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Curve">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="flat" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="moreCurved" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="baseCurve" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="planoConcave" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="planoConvex" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="biConcave" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="biConvex" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Curve", propOrder = {
    "flat",
    "moreCurved",
    "baseCurve",
    "planoConcave",
    "planoConvex",
    "biConcave",
    "biConvex"
})
public class Curve {

    protected Boolean flat;
    protected Boolean moreCurved;
    protected Float baseCurve;
    protected Boolean planoConcave;
    protected Boolean planoConvex;
    protected Boolean biConcave;
    protected Boolean biConvex;

    /**
     * Gets the value of the flat property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isFlat() {
        return flat;
    }

    /**
     * Sets the value of the flat property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setFlat(Boolean value) {
        this.flat = value;
    }

    /**
     * Gets the value of the moreCurved property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isMoreCurved() {
        return moreCurved;
    }

    /**
     * Sets the value of the moreCurved property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setMoreCurved(Boolean value) {
        this.moreCurved = value;
    }

    /**
     * Gets the value of the baseCurve property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getBaseCurve() {
        return baseCurve;
    }

    /**
     * Sets the value of the baseCurve property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setBaseCurve(Float value) {
        this.baseCurve = value;
    }

    /**
     * Gets the value of the planoConcave property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPlanoConcave() {
        return planoConcave;
    }

    /**
     * Sets the value of the planoConcave property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPlanoConcave(Boolean value) {
        this.planoConcave = value;
    }

    /**
     * Gets the value of the planoConvex property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPlanoConvex() {
        return planoConvex;
    }

    /**
     * Sets the value of the planoConvex property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPlanoConvex(Boolean value) {
        this.planoConvex = value;
    }

    /**
     * Gets the value of the biConcave property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isBiConcave() {
        return biConcave;
    }

    /**
     * Sets the value of the biConcave property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setBiConcave(Boolean value) {
        this.biConcave = value;
    }

    /**
     * Gets the value of the biConvex property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isBiConvex() {
        return biConvex;
    }

    /**
     * Sets the value of the biConvex property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setBiConvex(Boolean value) {
        this.biConvex = value;
    }

}
