//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.19 at 07:48:00 PM CEST 
//


package essilor.integrator.adapter.domain.b2boptic;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Decentration complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Decentration">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;sequence>
 *           &lt;element name="length" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *           &lt;element name="direction" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;/sequence>
 *         &lt;sequence>
 *           &lt;element name="horizontal" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *           &lt;element name="vertical" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;/sequence>
 *         &lt;sequence>
 *           &lt;element name="hdec" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;/sequence>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Decentration", propOrder = {
    "length",
    "direction",
    "horizontal",
    "vertical",
    "hdec"
})
public class Decentration {

    protected Float length;
    protected BigInteger direction;
    protected Float horizontal;
    protected Float vertical;
    protected Float hdec;

    /**
     * Gets the value of the length property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getLength() {
        return length;
    }

    /**
     * Sets the value of the length property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setLength(Float value) {
        this.length = value;
    }

    /**
     * Gets the value of the direction property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDirection() {
        return direction;
    }

    /**
     * Sets the value of the direction property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDirection(BigInteger value) {
        this.direction = value;
    }

    /**
     * Gets the value of the horizontal property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getHorizontal() {
        return horizontal;
    }

    /**
     * Sets the value of the horizontal property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setHorizontal(Float value) {
        this.horizontal = value;
    }

    /**
     * Gets the value of the vertical property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getVertical() {
        return vertical;
    }

    /**
     * Sets the value of the vertical property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setVertical(Float value) {
        this.vertical = value;
    }

    /**
     * Gets the value of the hdec property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getHdec() {
        return hdec;
    }

    /**
     * Sets the value of the hdec property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setHdec(Float value) {
        this.hdec = value;
    }

}
