//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.19 at 07:48:00 PM CEST 
//


package essilor.integrator.adapter.domain.b2boptic;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DrillHoles complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DrillHoles">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="pDrillHole" maxOccurs="10">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="point" type="{}PPoint" maxOccurs="2"/>
 *                   &lt;element name="depth" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *                   &lt;element name="diameterHole" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="cDrillHole" maxOccurs="10">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="point" type="{}CPoint" maxOccurs="2"/>
 *                   &lt;element name="depth" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *                   &lt;element name="diameterHole" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DrillHoles", propOrder = {
    "pDrillHole",
    "cDrillHole"
})
@XmlSeeAlso({
    essilor.integrator.adapter.domain.b2boptic.Frame.DrillHoles.class
})
public class DrillHoles {

    protected List<DrillHoles.PDrillHole> pDrillHole;
    protected List<DrillHoles.CDrillHole> cDrillHole;

    /**
     * Gets the value of the pDrillHole property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the pDrillHole property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPDrillHole().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DrillHoles.PDrillHole }
     * 
     * 
     */
    public List<DrillHoles.PDrillHole> getPDrillHole() {
        if (pDrillHole == null) {
            pDrillHole = new ArrayList<DrillHoles.PDrillHole>();
        }
        return this.pDrillHole;
    }

    /**
     * Gets the value of the cDrillHole property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cDrillHole property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCDrillHole().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DrillHoles.CDrillHole }
     * 
     * 
     */
    public List<DrillHoles.CDrillHole> getCDrillHole() {
        if (cDrillHole == null) {
            cDrillHole = new ArrayList<DrillHoles.CDrillHole>();
        }
        return this.cDrillHole;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="point" type="{}CPoint" maxOccurs="2"/>
     *         &lt;element name="depth" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
     *         &lt;element name="diameterHole" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "point",
        "depth",
        "diameterHole"
    })
    public static class CDrillHole {

        @XmlElement(required = true)
        protected List<CPoint> point;
        protected Float depth;
        protected Float diameterHole;

        /**
         * Gets the value of the point property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the point property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPoint().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link CPoint }
         * 
         * 
         */
        public List<CPoint> getPoint() {
            if (point == null) {
                point = new ArrayList<CPoint>();
            }
            return this.point;
        }

        /**
         * Gets the value of the depth property.
         * 
         * @return
         *     possible object is
         *     {@link Float }
         *     
         */
        public Float getDepth() {
            return depth;
        }

        /**
         * Sets the value of the depth property.
         * 
         * @param value
         *     allowed object is
         *     {@link Float }
         *     
         */
        public void setDepth(Float value) {
            this.depth = value;
        }

        /**
         * Gets the value of the diameterHole property.
         * 
         * @return
         *     possible object is
         *     {@link Float }
         *     
         */
        public Float getDiameterHole() {
            return diameterHole;
        }

        /**
         * Sets the value of the diameterHole property.
         * 
         * @param value
         *     allowed object is
         *     {@link Float }
         *     
         */
        public void setDiameterHole(Float value) {
            this.diameterHole = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="point" type="{}PPoint" maxOccurs="2"/>
     *         &lt;element name="depth" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
     *         &lt;element name="diameterHole" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "point",
        "depth",
        "diameterHole"
    })
    public static class PDrillHole {

        @XmlElement(required = true)
        protected List<PPoint> point;
        protected Float depth;
        protected Float diameterHole;

        /**
         * Gets the value of the point property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the point property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPoint().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link PPoint }
         * 
         * 
         */
        public List<PPoint> getPoint() {
            if (point == null) {
                point = new ArrayList<PPoint>();
            }
            return this.point;
        }

        /**
         * Gets the value of the depth property.
         * 
         * @return
         *     possible object is
         *     {@link Float }
         *     
         */
        public Float getDepth() {
            return depth;
        }

        /**
         * Sets the value of the depth property.
         * 
         * @param value
         *     allowed object is
         *     {@link Float }
         *     
         */
        public void setDepth(Float value) {
            this.depth = value;
        }

        /**
         * Gets the value of the diameterHole property.
         * 
         * @return
         *     possible object is
         *     {@link Float }
         *     
         */
        public Float getDiameterHole() {
            return diameterHole;
        }

        /**
         * Sets the value of the diameterHole property.
         * 
         * @param value
         *     allowed object is
         *     {@link Float }
         *     
         */
        public void setDiameterHole(Float value) {
            this.diameterHole = value;
        }

    }

}
