//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.19 at 07:48:00 PM CEST 
//


package essilor.integrator.adapter.domain.b2boptic;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for Edging complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Edging">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="bevel" type="{}Bevel"/>
 *         &lt;element name="polish" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="drilling" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="chamfer" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;>ChamferIntensity">
 *                 &lt;attribute name="position" type="{}ChamferPos" default="BOTH" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="edgingType" use="required" type="{}EdgingType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Edging", propOrder = {
    "bevel",
    "polish",
    "drilling",
    "chamfer"
})
public class Edging {

    @XmlElement(required = true)
    protected Bevel bevel;
    @XmlElement(defaultValue = "false")
    protected Boolean polish;
    @XmlElement(defaultValue = "false")
    protected Boolean drilling;
    protected Edging.Chamfer chamfer;
    @XmlAttribute(name = "edgingType", required = true)
    protected EdgingType edgingType;

    /**
     * Gets the value of the bevel property.
     * 
     * @return
     *     possible object is
     *     {@link Bevel }
     *     
     */
    public Bevel getBevel() {
        return bevel;
    }

    /**
     * Sets the value of the bevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link Bevel }
     *     
     */
    public void setBevel(Bevel value) {
        this.bevel = value;
    }

    /**
     * Gets the value of the polish property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPolish() {
        return polish;
    }

    /**
     * Sets the value of the polish property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPolish(Boolean value) {
        this.polish = value;
    }

    /**
     * Gets the value of the drilling property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDrilling() {
        return drilling;
    }

    /**
     * Sets the value of the drilling property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDrilling(Boolean value) {
        this.drilling = value;
    }

    /**
     * Gets the value of the chamfer property.
     * 
     * @return
     *     possible object is
     *     {@link Edging.Chamfer }
     *     
     */
    public Edging.Chamfer getChamfer() {
        return chamfer;
    }

    /**
     * Sets the value of the chamfer property.
     * 
     * @param value
     *     allowed object is
     *     {@link Edging.Chamfer }
     *     
     */
    public void setChamfer(Edging.Chamfer value) {
        this.chamfer = value;
    }

    /**
     * Gets the value of the edgingType property.
     * 
     * @return
     *     possible object is
     *     {@link EdgingType }
     *     
     */
    public EdgingType getEdgingType() {
        return edgingType;
    }

    /**
     * Sets the value of the edgingType property.
     * 
     * @param value
     *     allowed object is
     *     {@link EdgingType }
     *     
     */
    public void setEdgingType(EdgingType value) {
        this.edgingType = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;>ChamferIntensity">
     *       &lt;attribute name="position" type="{}ChamferPos" default="BOTH" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Chamfer {

        @XmlValue
        protected ChamferIntensity value;
        @XmlAttribute(name = "position")
        protected ChamferPos position;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link ChamferIntensity }
         *     
         */
        public ChamferIntensity getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link ChamferIntensity }
         *     
         */
        public void setValue(ChamferIntensity value) {
            this.value = value;
        }

        /**
         * Gets the value of the position property.
         * 
         * @return
         *     possible object is
         *     {@link ChamferPos }
         *     
         */
        public ChamferPos getPosition() {
            if (position == null) {
                return ChamferPos.BOTH;
            } else {
                return position;
            }
        }

        /**
         * Sets the value of the position property.
         * 
         * @param value
         *     allowed object is
         *     {@link ChamferPos }
         *     
         */
        public void setPosition(ChamferPos value) {
            this.position = value;
        }

    }

}
