//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.19 at 07:48:00 PM CEST 
//


package essilor.integrator.adapter.domain.b2boptic;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for Frame complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Frame">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="material" type="{}FrameMaterials"/>
 *         &lt;element name="manufacturer" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="brand" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="model" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="size" type="{}FrameSize" minOccurs="0"/>
 *         &lt;element name="color" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="commercialCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="shape" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;choice>
 *                     &lt;element name="catalog">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;sequence>
 *                               &lt;element name="shapeId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;/sequence>
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                     &lt;element name="explicit" maxOccurs="2">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;extension base="{}Shape">
 *                             &lt;attribute name="side" use="required" type="{}SidesSimple" />
 *                           &lt;/extension>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                     &lt;element name="tracerData" type="{}TracerData"/>
 *                   &lt;/choice>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="boxWidth" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="boxHeight" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="distanceBetweenLenses" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="drillHoles" maxOccurs="2" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{}DrillHoles">
 *                 &lt;attribute name="side" use="required" type="{}Sides" />
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="pantoscopicAngle" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>float">
 *                 &lt;attribute name="dimension" type="{}AngleDimension" default="DEG" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="frameBowAngle" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>float">
 *                 &lt;attribute name="dimension" type="{}AngleDimension" default="DEG" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="frameCurve" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="frameReferenceId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="quantity" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Frame", propOrder = {
    "material",
    "manufacturer",
    "brand",
    "model",
    "size",
    "color",
    "commercialCode",
    "shape",
    "boxWidth",
    "boxHeight",
    "distanceBetweenLenses",
    "drillHoles",
    "pantoscopicAngle",
    "frameBowAngle",
    "frameCurve",
    "frameReferenceId"
})
public class Frame {

    @XmlElement(required = true)
    protected FrameMaterials material;
    protected String manufacturer;
    protected String brand;
    protected String model;
    protected FrameSize size;
    protected String color;
    protected String commercialCode;
    protected Frame.Shape shape;
    protected Float boxWidth;
    protected Float boxHeight;
    protected Float distanceBetweenLenses;
    protected List<Frame.DrillHoles> drillHoles;
    protected Frame.PantoscopicAngle pantoscopicAngle;
    protected Frame.FrameBowAngle frameBowAngle;
    protected Float frameCurve;
    protected String frameReferenceId;
    @XmlAttribute(name = "quantity", required = true)
    protected BigInteger quantity;

    /**
     * Gets the value of the material property.
     * 
     * @return
     *     possible object is
     *     {@link FrameMaterials }
     *     
     */
    public FrameMaterials getMaterial() {
        return material;
    }

    /**
     * Sets the value of the material property.
     * 
     * @param value
     *     allowed object is
     *     {@link FrameMaterials }
     *     
     */
    public void setMaterial(FrameMaterials value) {
        this.material = value;
    }

    /**
     * Gets the value of the manufacturer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getManufacturer() {
        return manufacturer;
    }

    /**
     * Sets the value of the manufacturer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setManufacturer(String value) {
        this.manufacturer = value;
    }

    /**
     * Gets the value of the brand property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrand() {
        return brand;
    }

    /**
     * Sets the value of the brand property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBrand(String value) {
        this.brand = value;
    }

    /**
     * Gets the value of the model property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModel() {
        return model;
    }

    /**
     * Sets the value of the model property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModel(String value) {
        this.model = value;
    }

    /**
     * Gets the value of the size property.
     * 
     * @return
     *     possible object is
     *     {@link FrameSize }
     *     
     */
    public FrameSize getSize() {
        return size;
    }

    /**
     * Sets the value of the size property.
     * 
     * @param value
     *     allowed object is
     *     {@link FrameSize }
     *     
     */
    public void setSize(FrameSize value) {
        this.size = value;
    }

    /**
     * Gets the value of the color property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getColor() {
        return color;
    }

    /**
     * Sets the value of the color property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setColor(String value) {
        this.color = value;
    }

    /**
     * Gets the value of the commercialCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCommercialCode() {
        return commercialCode;
    }

    /**
     * Sets the value of the commercialCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCommercialCode(String value) {
        this.commercialCode = value;
    }

    /**
     * Gets the value of the shape property.
     * 
     * @return
     *     possible object is
     *     {@link Frame.Shape }
     *     
     */
    public Frame.Shape getShape() {
        return shape;
    }

    /**
     * Sets the value of the shape property.
     * 
     * @param value
     *     allowed object is
     *     {@link Frame.Shape }
     *     
     */
    public void setShape(Frame.Shape value) {
        this.shape = value;
    }

    /**
     * Gets the value of the boxWidth property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getBoxWidth() {
        return boxWidth;
    }

    /**
     * Sets the value of the boxWidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setBoxWidth(Float value) {
        this.boxWidth = value;
    }

    /**
     * Gets the value of the boxHeight property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getBoxHeight() {
        return boxHeight;
    }

    /**
     * Sets the value of the boxHeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setBoxHeight(Float value) {
        this.boxHeight = value;
    }

    /**
     * Gets the value of the distanceBetweenLenses property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getDistanceBetweenLenses() {
        return distanceBetweenLenses;
    }

    /**
     * Sets the value of the distanceBetweenLenses property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setDistanceBetweenLenses(Float value) {
        this.distanceBetweenLenses = value;
    }

    /**
     * Gets the value of the drillHoles property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the drillHoles property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDrillHoles().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Frame.DrillHoles }
     * 
     * 
     */
    public List<Frame.DrillHoles> getDrillHoles() {
        if (drillHoles == null) {
            drillHoles = new ArrayList<Frame.DrillHoles>();
        }
        return this.drillHoles;
    }

    /**
     * Gets the value of the pantoscopicAngle property.
     * 
     * @return
     *     possible object is
     *     {@link Frame.PantoscopicAngle }
     *     
     */
    public Frame.PantoscopicAngle getPantoscopicAngle() {
        return pantoscopicAngle;
    }

    /**
     * Sets the value of the pantoscopicAngle property.
     * 
     * @param value
     *     allowed object is
     *     {@link Frame.PantoscopicAngle }
     *     
     */
    public void setPantoscopicAngle(Frame.PantoscopicAngle value) {
        this.pantoscopicAngle = value;
    }

    /**
     * Gets the value of the frameBowAngle property.
     * 
     * @return
     *     possible object is
     *     {@link Frame.FrameBowAngle }
     *     
     */
    public Frame.FrameBowAngle getFrameBowAngle() {
        return frameBowAngle;
    }

    /**
     * Sets the value of the frameBowAngle property.
     * 
     * @param value
     *     allowed object is
     *     {@link Frame.FrameBowAngle }
     *     
     */
    public void setFrameBowAngle(Frame.FrameBowAngle value) {
        this.frameBowAngle = value;
    }

    /**
     * Gets the value of the frameCurve property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getFrameCurve() {
        return frameCurve;
    }

    /**
     * Sets the value of the frameCurve property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setFrameCurve(Float value) {
        this.frameCurve = value;
    }

    /**
     * Gets the value of the frameReferenceId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFrameReferenceId() {
        return frameReferenceId;
    }

    /**
     * Sets the value of the frameReferenceId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFrameReferenceId(String value) {
        this.frameReferenceId = value;
    }

    /**
     * Gets the value of the quantity property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getQuantity() {
        return quantity;
    }

    /**
     * Sets the value of the quantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setQuantity(BigInteger value) {
        this.quantity = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{}DrillHoles">
     *       &lt;attribute name="side" use="required" type="{}Sides" />
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class DrillHoles
        extends essilor.integrator.adapter.domain.b2boptic.DrillHoles
    {

        @XmlAttribute(name = "side", required = true)
        protected Sides side;

        /**
         * Gets the value of the side property.
         * 
         * @return
         *     possible object is
         *     {@link Sides }
         *     
         */
        public Sides getSide() {
            return side;
        }

        /**
         * Sets the value of the side property.
         * 
         * @param value
         *     allowed object is
         *     {@link Sides }
         *     
         */
        public void setSide(Sides value) {
            this.side = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>float">
     *       &lt;attribute name="dimension" type="{}AngleDimension" default="DEG" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class FrameBowAngle {

        @XmlValue
        protected float value;
        @XmlAttribute(name = "dimension")
        protected AngleDimension dimension;

        /**
         * Gets the value of the value property.
         * 
         */
        public float getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         */
        public void setValue(float value) {
            this.value = value;
        }

        /**
         * Gets the value of the dimension property.
         * 
         * @return
         *     possible object is
         *     {@link AngleDimension }
         *     
         */
        public AngleDimension getDimension() {
            if (dimension == null) {
                return AngleDimension.DEG;
            } else {
                return dimension;
            }
        }

        /**
         * Sets the value of the dimension property.
         * 
         * @param value
         *     allowed object is
         *     {@link AngleDimension }
         *     
         */
        public void setDimension(AngleDimension value) {
            this.dimension = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>float">
     *       &lt;attribute name="dimension" type="{}AngleDimension" default="DEG" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class PantoscopicAngle {

        @XmlValue
        protected float value;
        @XmlAttribute(name = "dimension")
        protected AngleDimension dimension;

        /**
         * Gets the value of the value property.
         * 
         */
        public float getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         */
        public void setValue(float value) {
            this.value = value;
        }

        /**
         * Gets the value of the dimension property.
         * 
         * @return
         *     possible object is
         *     {@link AngleDimension }
         *     
         */
        public AngleDimension getDimension() {
            if (dimension == null) {
                return AngleDimension.DEG;
            } else {
                return dimension;
            }
        }

        /**
         * Sets the value of the dimension property.
         * 
         * @param value
         *     allowed object is
         *     {@link AngleDimension }
         *     
         */
        public void setDimension(AngleDimension value) {
            this.dimension = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;choice>
     *           &lt;element name="catalog">
     *             &lt;complexType>
     *               &lt;complexContent>
     *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                   &lt;sequence>
     *                     &lt;element name="shapeId" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;/sequence>
     *                 &lt;/restriction>
     *               &lt;/complexContent>
     *             &lt;/complexType>
     *           &lt;/element>
     *           &lt;element name="explicit" maxOccurs="2">
     *             &lt;complexType>
     *               &lt;complexContent>
     *                 &lt;extension base="{}Shape">
     *                   &lt;attribute name="side" use="required" type="{}SidesSimple" />
     *                 &lt;/extension>
     *               &lt;/complexContent>
     *             &lt;/complexType>
     *           &lt;/element>
     *           &lt;element name="tracerData" type="{}TracerData"/>
     *         &lt;/choice>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "catalog",
        "explicit",
        "tracerData"
    })
    public static class Shape {

        protected Frame.Shape.Catalog catalog;
        protected List<Frame.Shape.Explicit> explicit;
        protected TracerData tracerData;

        /**
         * Gets the value of the catalog property.
         * 
         * @return
         *     possible object is
         *     {@link Frame.Shape.Catalog }
         *     
         */
        public Frame.Shape.Catalog getCatalog() {
            return catalog;
        }

        /**
         * Sets the value of the catalog property.
         * 
         * @param value
         *     allowed object is
         *     {@link Frame.Shape.Catalog }
         *     
         */
        public void setCatalog(Frame.Shape.Catalog value) {
            this.catalog = value;
        }

        /**
         * Gets the value of the explicit property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the explicit property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getExplicit().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Frame.Shape.Explicit }
         * 
         * 
         */
        public List<Frame.Shape.Explicit> getExplicit() {
            if (explicit == null) {
                explicit = new ArrayList<Frame.Shape.Explicit>();
            }
            return this.explicit;
        }

        /**
         * Gets the value of the tracerData property.
         * 
         * @return
         *     possible object is
         *     {@link TracerData }
         *     
         */
        public TracerData getTracerData() {
            return tracerData;
        }

        /**
         * Sets the value of the tracerData property.
         * 
         * @param value
         *     allowed object is
         *     {@link TracerData }
         *     
         */
        public void setTracerData(TracerData value) {
            this.tracerData = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="shapeId" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "shapeId"
        })
        public static class Catalog {

            @XmlElement(required = true)
            protected String shapeId;

            /**
             * Gets the value of the shapeId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getShapeId() {
                return shapeId;
            }

            /**
             * Sets the value of the shapeId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setShapeId(String value) {
                this.shapeId = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;extension base="{}Shape">
         *       &lt;attribute name="side" use="required" type="{}SidesSimple" />
         *     &lt;/extension>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Explicit
            extends essilor.integrator.adapter.domain.b2boptic.Shape
        {

            @XmlAttribute(name = "side", required = true)
            protected SidesSimple side;

            /**
             * Gets the value of the side property.
             * 
             * @return
             *     possible object is
             *     {@link SidesSimple }
             *     
             */
            public SidesSimple getSide() {
                return side;
            }

            /**
             * Sets the value of the side property.
             * 
             * @param value
             *     allowed object is
             *     {@link SidesSimple }
             *     
             */
            public void setSide(SidesSimple value) {
                this.side = value;
            }

        }

    }

}
