//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.19 at 07:48:00 PM CEST 
//


package essilor.integrator.adapter.domain.b2boptic;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for IProfilerMap complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IProfilerMap">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence maxOccurs="unbounded">
 *         &lt;element name="point">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="x" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                   &lt;element name="y" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                   &lt;element name="z" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IProfilerMap", propOrder = {
    "point"
})
public class IProfilerMap {

    @XmlElement(required = true)
    protected List<IProfilerMap.Point> point;

    /**
     * Gets the value of the point property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the point property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPoint().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IProfilerMap.Point }
     * 
     * 
     */
    public List<IProfilerMap.Point> getPoint() {
        if (point == null) {
            point = new ArrayList<IProfilerMap.Point>();
        }
        return this.point;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="x" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *         &lt;element name="y" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *         &lt;element name="z" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "x",
        "y",
        "z"
    })
    public static class Point {

        protected float x;
        protected float y;
        protected float z;

        /**
         * Gets the value of the x property.
         * 
         */
        public float getX() {
            return x;
        }

        /**
         * Sets the value of the x property.
         * 
         */
        public void setX(float value) {
            this.x = value;
        }

        /**
         * Gets the value of the y property.
         * 
         */
        public float getY() {
            return y;
        }

        /**
         * Sets the value of the y property.
         * 
         */
        public void setY(float value) {
            this.y = value;
        }

        /**
         * Gets the value of the z property.
         * 
         */
        public float getZ() {
            return z;
        }

        /**
         * Sets the value of the z property.
         * 
         */
        public void setZ(float value) {
            this.z = value;
        }

    }

}
