//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.19 at 07:48:00 PM CEST 
//


package essilor.integrator.adapter.domain.b2boptic;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Lens complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Lens">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="commercialCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="stockLens" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="ignoreFlags" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;choice>
 *           &lt;element name="rxData" type="{}RXDataType"/>
 *           &lt;element name="rxDataFn" type="{}RXDataTypeFarNear" maxOccurs="2"/>
 *         &lt;/choice>
 *         &lt;element name="coating" type="{}Coating" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="centration" type="{}Centration" minOccurs="0"/>
 *         &lt;element name="geometry" type="{}GeometryType"/>
 *         &lt;element name="options" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;choice minOccurs="0">
 *                     &lt;element name="occlusion" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                     &lt;element name="frosted" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                   &lt;/choice>
 *                   &lt;element name="slabOff" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="frameFit" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="engraving" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="branding" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="experimental" type="{http://www.w3.org/2001/XMLSchema}anyType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="side" use="required" type="{}Sides" />
 *       &lt;attribute name="balancingLens" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="virtualLens" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Lens", propOrder = {
    "commercialCode",
    "stockLens",
    "ignoreFlags",
    "rxData",
    "rxDataFn",
    "coating",
    "centration",
    "geometry",
    "options",
    "frameFit",
    "engraving",
    "branding",
    "experimental"
})
@XmlSeeAlso({
    essilor.integrator.adapter.domain.b2boptic.Pair.Lens.class
})
public class Lens {

    @XmlElement(required = true)
    protected String commercialCode;
    @XmlElement(defaultValue = "false")
    protected Boolean stockLens;
    protected List<String> ignoreFlags;
    protected RXDataType rxData;
    protected List<RXDataTypeFarNear> rxDataFn;
    protected List<Coating> coating;
    protected Centration centration;
    @XmlElement(required = true)
    protected GeometryType geometry;
    protected Lens.Options options;
    protected Float frameFit;
    protected String engraving;
    @XmlElement(defaultValue = "false")
    protected Boolean branding;
    protected List<Object> experimental;
    @XmlAttribute(name = "side", required = true)
    protected Sides side;
    @XmlAttribute(name = "balancingLens")
    protected Boolean balancingLens;
    @XmlAttribute(name = "virtualLens")
    protected Boolean virtualLens;

    /**
     * Gets the value of the commercialCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCommercialCode() {
        return commercialCode;
    }

    /**
     * Sets the value of the commercialCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCommercialCode(String value) {
        this.commercialCode = value;
    }

    /**
     * Gets the value of the stockLens property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isStockLens() {
        return stockLens;
    }

    /**
     * Sets the value of the stockLens property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setStockLens(Boolean value) {
        this.stockLens = value;
    }

    /**
     * Gets the value of the ignoreFlags property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ignoreFlags property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIgnoreFlags().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getIgnoreFlags() {
        if (ignoreFlags == null) {
            ignoreFlags = new ArrayList<String>();
        }
        return this.ignoreFlags;
    }

    /**
     * Gets the value of the rxData property.
     * 
     * @return
     *     possible object is
     *     {@link RXDataType }
     *     
     */
    public RXDataType getRxData() {
        return rxData;
    }

    /**
     * Sets the value of the rxData property.
     * 
     * @param value
     *     allowed object is
     *     {@link RXDataType }
     *     
     */
    public void setRxData(RXDataType value) {
        this.rxData = value;
    }

    /**
     * Gets the value of the rxDataFn property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the rxDataFn property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRxDataFn().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RXDataTypeFarNear }
     * 
     * 
     */
    public List<RXDataTypeFarNear> getRxDataFn() {
        if (rxDataFn == null) {
            rxDataFn = new ArrayList<RXDataTypeFarNear>();
        }
        return this.rxDataFn;
    }

    /**
     * Gets the value of the coating property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the coating property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCoating().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Coating }
     * 
     * 
     */
    public List<Coating> getCoating() {
        if (coating == null) {
            coating = new ArrayList<Coating>();
        }
        return this.coating;
    }

    /**
     * Gets the value of the centration property.
     * 
     * @return
     *     possible object is
     *     {@link Centration }
     *     
     */
    public Centration getCentration() {
        return centration;
    }

    /**
     * Sets the value of the centration property.
     * 
     * @param value
     *     allowed object is
     *     {@link Centration }
     *     
     */
    public void setCentration(Centration value) {
        this.centration = value;
    }

    /**
     * Gets the value of the geometry property.
     * 
     * @return
     *     possible object is
     *     {@link GeometryType }
     *     
     */
    public GeometryType getGeometry() {
        return geometry;
    }

    /**
     * Sets the value of the geometry property.
     * 
     * @param value
     *     allowed object is
     *     {@link GeometryType }
     *     
     */
    public void setGeometry(GeometryType value) {
        this.geometry = value;
    }

    /**
     * Gets the value of the options property.
     * 
     * @return
     *     possible object is
     *     {@link Lens.Options }
     *     
     */
    public Lens.Options getOptions() {
        return options;
    }

    /**
     * Sets the value of the options property.
     * 
     * @param value
     *     allowed object is
     *     {@link Lens.Options }
     *     
     */
    public void setOptions(Lens.Options value) {
        this.options = value;
    }

    /**
     * Gets the value of the frameFit property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getFrameFit() {
        return frameFit;
    }

    /**
     * Sets the value of the frameFit property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setFrameFit(Float value) {
        this.frameFit = value;
    }

    /**
     * Gets the value of the engraving property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEngraving() {
        return engraving;
    }

    /**
     * Sets the value of the engraving property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEngraving(String value) {
        this.engraving = value;
    }

    /**
     * Gets the value of the branding property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isBranding() {
        return branding;
    }

    /**
     * Sets the value of the branding property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setBranding(Boolean value) {
        this.branding = value;
    }

    /**
     * Gets the value of the experimental property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the experimental property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExperimental().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * 
     * 
     */
    public List<Object> getExperimental() {
        if (experimental == null) {
            experimental = new ArrayList<Object>();
        }
        return this.experimental;
    }

    /**
     * Gets the value of the side property.
     * 
     * @return
     *     possible object is
     *     {@link Sides }
     *     
     */
    public Sides getSide() {
        return side;
    }

    /**
     * Sets the value of the side property.
     * 
     * @param value
     *     allowed object is
     *     {@link Sides }
     *     
     */
    public void setSide(Sides value) {
        this.side = value;
    }

    /**
     * Gets the value of the balancingLens property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isBalancingLens() {
        if (balancingLens == null) {
            return false;
        } else {
            return balancingLens;
        }
    }

    /**
     * Sets the value of the balancingLens property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setBalancingLens(Boolean value) {
        this.balancingLens = value;
    }

    /**
     * Gets the value of the virtualLens property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isVirtualLens() {
        if (virtualLens == null) {
            return false;
        } else {
            return virtualLens;
        }
    }

    /**
     * Sets the value of the virtualLens property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setVirtualLens(Boolean value) {
        this.virtualLens = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;choice minOccurs="0">
     *           &lt;element name="occlusion" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *           &lt;element name="frosted" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *         &lt;/choice>
     *         &lt;element name="slabOff" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "occlusion",
        "frosted",
        "slabOff"
    })
    public static class Options {

        protected Boolean occlusion;
        protected Boolean frosted;
        @XmlElement(defaultValue = "false")
        protected Boolean slabOff;

        /**
         * Gets the value of the occlusion property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isOcclusion() {
            return occlusion;
        }

        /**
         * Sets the value of the occlusion property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setOcclusion(Boolean value) {
            this.occlusion = value;
        }

        /**
         * Gets the value of the frosted property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isFrosted() {
            return frosted;
        }

        /**
         * Sets the value of the frosted property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setFrosted(Boolean value) {
            this.frosted = value;
        }

        /**
         * Gets the value of the slabOff property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isSlabOff() {
            return slabOff;
        }

        /**
         * Sets the value of the slabOff property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setSlabOff(Boolean value) {
            this.slabOff = value;
        }

    }

}
