//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.19 at 07:48:00 PM CEST 
//


package essilor.integrator.adapter.domain.b2boptic;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for Patient complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Patient">
 *   &lt;complexContent>
 *     &lt;extension base="{}Account">
 *       &lt;sequence minOccurs="0">
 *         &lt;element name="mailAllowed" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="gender" type="{}Gender" minOccurs="0"/>
 *         &lt;element name="dateOfBirth" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;sequence minOccurs="0">
 *           &lt;element name="interpupillaryDistanceRight" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *           &lt;element name="interpupillaryDistanceLeft" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;/sequence>
 *         &lt;element name="nearObjectDistance" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="middleObjectDistance" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="farObjectDistance" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="nearRefractionDistance" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="additionRefractionMethod" type="{}AdditionRefractionMethod" minOccurs="0"/>
 *         &lt;element name="backVertexDistanceRefraction" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="iProfilerData" type="{}IProfilerData" minOccurs="0"/>
 *         &lt;element name="headTilt" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="ipseo" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="he" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                   &lt;element name="st" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="headCape" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="applianceWeight" type="{}ApplianceWeight" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Patient", propOrder = {
    "mailAllowed",
    "gender",
    "dateOfBirth",
    "interpupillaryDistanceRight",
    "interpupillaryDistanceLeft",
    "nearObjectDistance",
    "middleObjectDistance",
    "farObjectDistance",
    "nearRefractionDistance",
    "additionRefractionMethod",
    "backVertexDistanceRefraction",
    "iProfilerData",
    "headTilt",
    "ipseo",
    "headCape",
    "applianceWeight"
})
public class Patient
    extends Account
{

    @XmlElement(defaultValue = "false")
    protected Boolean mailAllowed;
    protected Gender gender;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dateOfBirth;
    protected Float interpupillaryDistanceRight;
    protected Float interpupillaryDistanceLeft;
    protected Float nearObjectDistance;
    protected Float middleObjectDistance;
    protected Float farObjectDistance;
    protected Float nearRefractionDistance;
    protected AdditionRefractionMethod additionRefractionMethod;
    protected Float backVertexDistanceRefraction;
    protected IProfilerData iProfilerData;
    protected Float headTilt;
    protected Patient.Ipseo ipseo;
    protected Float headCape;
    protected ApplianceWeight applianceWeight;

    /**
     * Gets the value of the mailAllowed property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isMailAllowed() {
        return mailAllowed;
    }

    /**
     * Sets the value of the mailAllowed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setMailAllowed(Boolean value) {
        this.mailAllowed = value;
    }

    /**
     * Gets the value of the gender property.
     * 
     * @return
     *     possible object is
     *     {@link Gender }
     *     
     */
    public Gender getGender() {
        return gender;
    }

    /**
     * Sets the value of the gender property.
     * 
     * @param value
     *     allowed object is
     *     {@link Gender }
     *     
     */
    public void setGender(Gender value) {
        this.gender = value;
    }

    /**
     * Gets the value of the dateOfBirth property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateOfBirth() {
        return dateOfBirth;
    }

    /**
     * Sets the value of the dateOfBirth property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateOfBirth(XMLGregorianCalendar value) {
        this.dateOfBirth = value;
    }

    /**
     * Gets the value of the interpupillaryDistanceRight property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getInterpupillaryDistanceRight() {
        return interpupillaryDistanceRight;
    }

    /**
     * Sets the value of the interpupillaryDistanceRight property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setInterpupillaryDistanceRight(Float value) {
        this.interpupillaryDistanceRight = value;
    }

    /**
     * Gets the value of the interpupillaryDistanceLeft property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getInterpupillaryDistanceLeft() {
        return interpupillaryDistanceLeft;
    }

    /**
     * Sets the value of the interpupillaryDistanceLeft property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setInterpupillaryDistanceLeft(Float value) {
        this.interpupillaryDistanceLeft = value;
    }

    /**
     * Gets the value of the nearObjectDistance property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getNearObjectDistance() {
        return nearObjectDistance;
    }

    /**
     * Sets the value of the nearObjectDistance property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setNearObjectDistance(Float value) {
        this.nearObjectDistance = value;
    }

    /**
     * Gets the value of the middleObjectDistance property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getMiddleObjectDistance() {
        return middleObjectDistance;
    }

    /**
     * Sets the value of the middleObjectDistance property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setMiddleObjectDistance(Float value) {
        this.middleObjectDistance = value;
    }

    /**
     * Gets the value of the farObjectDistance property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getFarObjectDistance() {
        return farObjectDistance;
    }

    /**
     * Sets the value of the farObjectDistance property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setFarObjectDistance(Float value) {
        this.farObjectDistance = value;
    }

    /**
     * Gets the value of the nearRefractionDistance property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getNearRefractionDistance() {
        return nearRefractionDistance;
    }

    /**
     * Sets the value of the nearRefractionDistance property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setNearRefractionDistance(Float value) {
        this.nearRefractionDistance = value;
    }

    /**
     * Gets the value of the additionRefractionMethod property.
     * 
     * @return
     *     possible object is
     *     {@link AdditionRefractionMethod }
     *     
     */
    public AdditionRefractionMethod getAdditionRefractionMethod() {
        return additionRefractionMethod;
    }

    /**
     * Sets the value of the additionRefractionMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdditionRefractionMethod }
     *     
     */
    public void setAdditionRefractionMethod(AdditionRefractionMethod value) {
        this.additionRefractionMethod = value;
    }

    /**
     * Gets the value of the backVertexDistanceRefraction property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getBackVertexDistanceRefraction() {
        return backVertexDistanceRefraction;
    }

    /**
     * Sets the value of the backVertexDistanceRefraction property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setBackVertexDistanceRefraction(Float value) {
        this.backVertexDistanceRefraction = value;
    }

    /**
     * Gets the value of the iProfilerData property.
     * 
     * @return
     *     possible object is
     *     {@link IProfilerData }
     *     
     */
    public IProfilerData getIProfilerData() {
        return iProfilerData;
    }

    /**
     * Sets the value of the iProfilerData property.
     * 
     * @param value
     *     allowed object is
     *     {@link IProfilerData }
     *     
     */
    public void setIProfilerData(IProfilerData value) {
        this.iProfilerData = value;
    }

    /**
     * Gets the value of the headTilt property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getHeadTilt() {
        return headTilt;
    }

    /**
     * Sets the value of the headTilt property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setHeadTilt(Float value) {
        this.headTilt = value;
    }

    /**
     * Gets the value of the ipseo property.
     * 
     * @return
     *     possible object is
     *     {@link Patient.Ipseo }
     *     
     */
    public Patient.Ipseo getIpseo() {
        return ipseo;
    }

    /**
     * Sets the value of the ipseo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Patient.Ipseo }
     *     
     */
    public void setIpseo(Patient.Ipseo value) {
        this.ipseo = value;
    }

    /**
     * Gets the value of the headCape property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getHeadCape() {
        return headCape;
    }

    /**
     * Sets the value of the headCape property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setHeadCape(Float value) {
        this.headCape = value;
    }

    /**
     * Gets the value of the applianceWeight property.
     * 
     * @return
     *     possible object is
     *     {@link ApplianceWeight }
     *     
     */
    public ApplianceWeight getApplianceWeight() {
        return applianceWeight;
    }

    /**
     * Sets the value of the applianceWeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link ApplianceWeight }
     *     
     */
    public void setApplianceWeight(ApplianceWeight value) {
        this.applianceWeight = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="he" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *         &lt;element name="st" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "he",
        "st"
    })
    public static class Ipseo {

        protected float he;
        protected float st;

        /**
         * Gets the value of the he property.
         * 
         */
        public float getHe() {
            return he;
        }

        /**
         * Sets the value of the he property.
         * 
         */
        public void setHe(float value) {
            this.he = value;
        }

        /**
         * Gets the value of the st property.
         * 
         */
        public float getSt() {
            return st;
        }

        /**
         * Sets the value of the st property.
         * 
         */
        public void setSt(float value) {
            this.st = value;
        }

    }

}
