//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.19 at 07:48:00 PM CEST 
//


package essilor.integrator.adapter.domain.b2boptic;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RXDataTypeSimple complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RXDataTypeSimple">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="sphere" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="cylinder" type="{}Cylinder" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RXDataTypeSimple", propOrder = {
    "sphere",
    "cylinder"
})
public class RXDataTypeSimple {

    protected float sphere;
    protected Cylinder cylinder;

    /**
     * Gets the value of the sphere property.
     * 
     */
    public float getSphere() {
        return sphere;
    }

    /**
     * Sets the value of the sphere property.
     * 
     */
    public void setSphere(float value) {
        this.sphere = value;
    }

    /**
     * Gets the value of the cylinder property.
     * 
     * @return
     *     possible object is
     *     {@link Cylinder }
     *     
     */
    public Cylinder getCylinder() {
        return cylinder;
    }

    /**
     * Sets the value of the cylinder property.
     * 
     * @param value
     *     allowed object is
     *     {@link Cylinder }
     *     
     */
    public void setCylinder(Cylinder value) {
        this.cylinder = value;
    }

}
