//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.19 at 07:48:00 PM CEST 
//


package essilor.integrator.adapter.domain.b2boptic;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RXDataTypeFarNear complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RXDataTypeFarNear">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="far" type="{}RXDataTypeFn"/>
 *         &lt;element name="near" type="{}RXDataTypeFn"/>
 *       &lt;/sequence>
 *       &lt;attribute name="reference" use="required" type="{}RxDataReferences" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RXDataTypeFarNear", propOrder = {
    "far",
    "near"
})
public class RXDataTypeFarNear {

    @XmlElement(required = true)
    protected RXDataTypeFn far;
    @XmlElement(required = true)
    protected RXDataTypeFn near;
    @XmlAttribute(name = "reference", required = true)
    protected RxDataReferences reference;

    /**
     * Gets the value of the far property.
     * 
     * @return
     *     possible object is
     *     {@link RXDataTypeFn }
     *     
     */
    public RXDataTypeFn getFar() {
        return far;
    }

    /**
     * Sets the value of the far property.
     * 
     * @param value
     *     allowed object is
     *     {@link RXDataTypeFn }
     *     
     */
    public void setFar(RXDataTypeFn value) {
        this.far = value;
    }

    /**
     * Gets the value of the near property.
     * 
     * @return
     *     possible object is
     *     {@link RXDataTypeFn }
     *     
     */
    public RXDataTypeFn getNear() {
        return near;
    }

    /**
     * Sets the value of the near property.
     * 
     * @param value
     *     allowed object is
     *     {@link RXDataTypeFn }
     *     
     */
    public void setNear(RXDataTypeFn value) {
        this.near = value;
    }

    /**
     * Gets the value of the reference property.
     * 
     * @return
     *     possible object is
     *     {@link RxDataReferences }
     *     
     */
    public RxDataReferences getReference() {
        return reference;
    }

    /**
     * Sets the value of the reference property.
     * 
     * @param value
     *     allowed object is
     *     {@link RxDataReferences }
     *     
     */
    public void setReference(RxDataReferences value) {
        this.reference = value;
    }

}
