//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.19 at 07:48:00 PM CEST 
//


package essilor.integrator.adapter.domain.b2boptic;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RXDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RXDataType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="sphere" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="cylinder" type="{}Cylinder" minOccurs="0"/>
 *         &lt;element name="addition" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="prism" type="{}Prism" maxOccurs="2" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RXDataType", propOrder = {
    "sphere",
    "cylinder",
    "addition",
    "prism"
})
public class RXDataType {

    protected float sphere;
    protected Cylinder cylinder;
    protected Float addition;
    protected List<Prism> prism;

    /**
     * Gets the value of the sphere property.
     * 
     */
    public float getSphere() {
        return sphere;
    }

    /**
     * Sets the value of the sphere property.
     * 
     */
    public void setSphere(float value) {
        this.sphere = value;
    }

    /**
     * Gets the value of the cylinder property.
     * 
     * @return
     *     possible object is
     *     {@link Cylinder }
     *     
     */
    public Cylinder getCylinder() {
        return cylinder;
    }

    /**
     * Sets the value of the cylinder property.
     * 
     * @param value
     *     allowed object is
     *     {@link Cylinder }
     *     
     */
    public void setCylinder(Cylinder value) {
        this.cylinder = value;
    }

    /**
     * Gets the value of the addition property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getAddition() {
        return addition;
    }

    /**
     * Sets the value of the addition property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setAddition(Float value) {
        this.addition = value;
    }

    /**
     * Gets the value of the prism property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the prism property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPrism().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Prism }
     * 
     * 
     */
    public List<Prism> getPrism() {
        if (prism == null) {
            prism = new ArrayList<Prism>();
        }
        return this.prism;
    }

}
