//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.19 at 07:48:00 PM CEST 
//


package essilor.integrator.adapter.domain.b2boptic;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for StockLens complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="StockLens">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="commercialCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="rxData" type="{}RXDataType4SL"/>
 *         &lt;element name="coating" type="{}Coating" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="diameter" type="{}Diameter"/>
 *       &lt;/sequence>
 *       &lt;attribute name="quantity" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="side" use="required" type="{}Sides" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StockLens", propOrder = {
    "commercialCode",
    "rxData",
    "coating",
    "diameter"
})
public class StockLens {

    @XmlElement(required = true)
    protected String commercialCode;
    @XmlElement(required = true)
    protected RXDataType4SL rxData;
    protected List<Coating> coating;
    @XmlElement(required = true)
    protected Diameter diameter;
    @XmlAttribute(name = "quantity", required = true)
    protected BigInteger quantity;
    @XmlAttribute(name = "side", required = true)
    protected Sides side;

    /**
     * Gets the value of the commercialCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCommercialCode() {
        return commercialCode;
    }

    /**
     * Sets the value of the commercialCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCommercialCode(String value) {
        this.commercialCode = value;
    }

    /**
     * Gets the value of the rxData property.
     * 
     * @return
     *     possible object is
     *     {@link RXDataType4SL }
     *     
     */
    public RXDataType4SL getRxData() {
        return rxData;
    }

    /**
     * Sets the value of the rxData property.
     * 
     * @param value
     *     allowed object is
     *     {@link RXDataType4SL }
     *     
     */
    public void setRxData(RXDataType4SL value) {
        this.rxData = value;
    }

    /**
     * Gets the value of the coating property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the coating property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCoating().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Coating }
     * 
     * 
     */
    public List<Coating> getCoating() {
        if (coating == null) {
            coating = new ArrayList<Coating>();
        }
        return this.coating;
    }

    /**
     * Gets the value of the diameter property.
     * 
     * @return
     *     possible object is
     *     {@link Diameter }
     *     
     */
    public Diameter getDiameter() {
        return diameter;
    }

    /**
     * Sets the value of the diameter property.
     * 
     * @param value
     *     allowed object is
     *     {@link Diameter }
     *     
     */
    public void setDiameter(Diameter value) {
        this.diameter = value;
    }

    /**
     * Gets the value of the quantity property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getQuantity() {
        return quantity;
    }

    /**
     * Sets the value of the quantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setQuantity(BigInteger value) {
        this.quantity = value;
    }

    /**
     * Gets the value of the side property.
     * 
     * @return
     *     possible object is
     *     {@link Sides }
     *     
     */
    public Sides getSide() {
        return side;
    }

    /**
     * Sets the value of the side property.
     * 
     * @param value
     *     allowed object is
     *     {@link Sides }
     *     
     */
    public void setSide(Sides value) {
        this.side = value;
    }

}
