//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.19 at 07:48:00 PM CEST 
//


package essilor.integrator.adapter.domain.b2boptic;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Zernikes complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Zernikes">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="zernikes7" type="{}Zernikes7"/>
 *         &lt;element name="zernikes8" type="{}Zernikes8"/>
 *         &lt;element name="zernikes9" type="{}Zernikes9"/>
 *         &lt;element name="zernikes10" type="{}Zernikes10"/>
 *         &lt;element name="zernikes11" type="{}Zernikes11"/>
 *         &lt;element name="zernikes12" type="{}Zernikes12"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Zernikes", propOrder = {
    "zernikes7",
    "zernikes8",
    "zernikes9",
    "zernikes10",
    "zernikes11",
    "zernikes12"
})
public class Zernikes {

    protected Zernikes7 zernikes7;
    protected Zernikes8 zernikes8;
    protected Zernikes9 zernikes9;
    protected Zernikes10 zernikes10;
    protected Zernikes11 zernikes11;
    protected Zernikes12 zernikes12;

    /**
     * Gets the value of the zernikes7 property.
     * 
     * @return
     *     possible object is
     *     {@link Zernikes7 }
     *     
     */
    public Zernikes7 getZernikes7() {
        return zernikes7;
    }

    /**
     * Sets the value of the zernikes7 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Zernikes7 }
     *     
     */
    public void setZernikes7(Zernikes7 value) {
        this.zernikes7 = value;
    }

    /**
     * Gets the value of the zernikes8 property.
     * 
     * @return
     *     possible object is
     *     {@link Zernikes8 }
     *     
     */
    public Zernikes8 getZernikes8() {
        return zernikes8;
    }

    /**
     * Sets the value of the zernikes8 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Zernikes8 }
     *     
     */
    public void setZernikes8(Zernikes8 value) {
        this.zernikes8 = value;
    }

    /**
     * Gets the value of the zernikes9 property.
     * 
     * @return
     *     possible object is
     *     {@link Zernikes9 }
     *     
     */
    public Zernikes9 getZernikes9() {
        return zernikes9;
    }

    /**
     * Sets the value of the zernikes9 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Zernikes9 }
     *     
     */
    public void setZernikes9(Zernikes9 value) {
        this.zernikes9 = value;
    }

    /**
     * Gets the value of the zernikes10 property.
     * 
     * @return
     *     possible object is
     *     {@link Zernikes10 }
     *     
     */
    public Zernikes10 getZernikes10() {
        return zernikes10;
    }

    /**
     * Sets the value of the zernikes10 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Zernikes10 }
     *     
     */
    public void setZernikes10(Zernikes10 value) {
        this.zernikes10 = value;
    }

    /**
     * Gets the value of the zernikes11 property.
     * 
     * @return
     *     possible object is
     *     {@link Zernikes11 }
     *     
     */
    public Zernikes11 getZernikes11() {
        return zernikes11;
    }

    /**
     * Sets the value of the zernikes11 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Zernikes11 }
     *     
     */
    public void setZernikes11(Zernikes11 value) {
        this.zernikes11 = value;
    }

    /**
     * Gets the value of the zernikes12 property.
     * 
     * @return
     *     possible object is
     *     {@link Zernikes12 }
     *     
     */
    public Zernikes12 getZernikes12() {
        return zernikes12;
    }

    /**
     * Sets the value of the zernikes12 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Zernikes12 }
     *     
     */
    public void setZernikes12(Zernikes12 value) {
        this.zernikes12 = value;
    }

}
