//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.19 at 07:48:00 PM CEST 
//


package essilor.integrator.adapter.domain.b2boptic;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Zernikes7 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Zernikes7">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="pupilDiameter" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="z_0_0" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="z_1_M1" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="z_1_1" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="z_2_M2" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="z_2_0" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="z_2_2" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="z_3_M3" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="z_3_M1" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="z_3_1" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="z_3_3" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="z_4_M4" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="z_4_M2" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="z_4_0" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="z_4_2" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="z_4_4" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="z_5_M5" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="z_5_M3" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="z_5_M1" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="z_5_1" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="z_5_3" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="z_5_5" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="z_6_M6" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="z_6_M4" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="z_6_M2" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="z_6_0" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="z_6_2" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="z_6_4" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="z_6_6" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="z_7_M7" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="z_7_M5" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="z_7_M3" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="z_7_M1" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="z_7_1" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="z_7_3" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="z_7_5" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="z_7_7" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Zernikes7", propOrder = {
    "pupilDiameter",
    "z00",
    "z1M1",
    "z11",
    "z2M2",
    "z20",
    "z22",
    "z3M3",
    "z3M1",
    "z31",
    "z33",
    "z4M4",
    "z4M2",
    "z40",
    "z42",
    "z44",
    "z5M5",
    "z5M3",
    "z5M1",
    "z51",
    "z53",
    "z55",
    "z6M6",
    "z6M4",
    "z6M2",
    "z60",
    "z62",
    "z64",
    "z66",
    "z7M7",
    "z7M5",
    "z7M3",
    "z7M1",
    "z71",
    "z73",
    "z75",
    "z77"
})
@XmlSeeAlso({
    Zernikes8 .class
})
public class Zernikes7 {

    protected float pupilDiameter;
    @XmlElement(name = "z_0_0")
    protected float z00;
    @XmlElement(name = "z_1_M1")
    protected float z1M1;
    @XmlElement(name = "z_1_1")
    protected float z11;
    @XmlElement(name = "z_2_M2")
    protected float z2M2;
    @XmlElement(name = "z_2_0")
    protected float z20;
    @XmlElement(name = "z_2_2")
    protected float z22;
    @XmlElement(name = "z_3_M3")
    protected float z3M3;
    @XmlElement(name = "z_3_M1")
    protected float z3M1;
    @XmlElement(name = "z_3_1")
    protected float z31;
    @XmlElement(name = "z_3_3")
    protected float z33;
    @XmlElement(name = "z_4_M4")
    protected float z4M4;
    @XmlElement(name = "z_4_M2")
    protected float z4M2;
    @XmlElement(name = "z_4_0")
    protected float z40;
    @XmlElement(name = "z_4_2")
    protected float z42;
    @XmlElement(name = "z_4_4")
    protected float z44;
    @XmlElement(name = "z_5_M5")
    protected float z5M5;
    @XmlElement(name = "z_5_M3")
    protected float z5M3;
    @XmlElement(name = "z_5_M1")
    protected float z5M1;
    @XmlElement(name = "z_5_1")
    protected float z51;
    @XmlElement(name = "z_5_3")
    protected float z53;
    @XmlElement(name = "z_5_5")
    protected float z55;
    @XmlElement(name = "z_6_M6")
    protected float z6M6;
    @XmlElement(name = "z_6_M4")
    protected float z6M4;
    @XmlElement(name = "z_6_M2")
    protected float z6M2;
    @XmlElement(name = "z_6_0")
    protected float z60;
    @XmlElement(name = "z_6_2")
    protected float z62;
    @XmlElement(name = "z_6_4")
    protected float z64;
    @XmlElement(name = "z_6_6")
    protected float z66;
    @XmlElement(name = "z_7_M7")
    protected float z7M7;
    @XmlElement(name = "z_7_M5")
    protected float z7M5;
    @XmlElement(name = "z_7_M3")
    protected float z7M3;
    @XmlElement(name = "z_7_M1")
    protected float z7M1;
    @XmlElement(name = "z_7_1")
    protected float z71;
    @XmlElement(name = "z_7_3")
    protected float z73;
    @XmlElement(name = "z_7_5")
    protected float z75;
    @XmlElement(name = "z_7_7")
    protected float z77;

    /**
     * Gets the value of the pupilDiameter property.
     * 
     */
    public float getPupilDiameter() {
        return pupilDiameter;
    }

    /**
     * Sets the value of the pupilDiameter property.
     * 
     */
    public void setPupilDiameter(float value) {
        this.pupilDiameter = value;
    }

    /**
     * Gets the value of the z00 property.
     * 
     */
    public float getZ00() {
        return z00;
    }

    /**
     * Sets the value of the z00 property.
     * 
     */
    public void setZ00(float value) {
        this.z00 = value;
    }

    /**
     * Gets the value of the z1M1 property.
     * 
     */
    public float getZ1M1() {
        return z1M1;
    }

    /**
     * Sets the value of the z1M1 property.
     * 
     */
    public void setZ1M1(float value) {
        this.z1M1 = value;
    }

    /**
     * Gets the value of the z11 property.
     * 
     */
    public float getZ11() {
        return z11;
    }

    /**
     * Sets the value of the z11 property.
     * 
     */
    public void setZ11(float value) {
        this.z11 = value;
    }

    /**
     * Gets the value of the z2M2 property.
     * 
     */
    public float getZ2M2() {
        return z2M2;
    }

    /**
     * Sets the value of the z2M2 property.
     * 
     */
    public void setZ2M2(float value) {
        this.z2M2 = value;
    }

    /**
     * Gets the value of the z20 property.
     * 
     */
    public float getZ20() {
        return z20;
    }

    /**
     * Sets the value of the z20 property.
     * 
     */
    public void setZ20(float value) {
        this.z20 = value;
    }

    /**
     * Gets the value of the z22 property.
     * 
     */
    public float getZ22() {
        return z22;
    }

    /**
     * Sets the value of the z22 property.
     * 
     */
    public void setZ22(float value) {
        this.z22 = value;
    }

    /**
     * Gets the value of the z3M3 property.
     * 
     */
    public float getZ3M3() {
        return z3M3;
    }

    /**
     * Sets the value of the z3M3 property.
     * 
     */
    public void setZ3M3(float value) {
        this.z3M3 = value;
    }

    /**
     * Gets the value of the z3M1 property.
     * 
     */
    public float getZ3M1() {
        return z3M1;
    }

    /**
     * Sets the value of the z3M1 property.
     * 
     */
    public void setZ3M1(float value) {
        this.z3M1 = value;
    }

    /**
     * Gets the value of the z31 property.
     * 
     */
    public float getZ31() {
        return z31;
    }

    /**
     * Sets the value of the z31 property.
     * 
     */
    public void setZ31(float value) {
        this.z31 = value;
    }

    /**
     * Gets the value of the z33 property.
     * 
     */
    public float getZ33() {
        return z33;
    }

    /**
     * Sets the value of the z33 property.
     * 
     */
    public void setZ33(float value) {
        this.z33 = value;
    }

    /**
     * Gets the value of the z4M4 property.
     * 
     */
    public float getZ4M4() {
        return z4M4;
    }

    /**
     * Sets the value of the z4M4 property.
     * 
     */
    public void setZ4M4(float value) {
        this.z4M4 = value;
    }

    /**
     * Gets the value of the z4M2 property.
     * 
     */
    public float getZ4M2() {
        return z4M2;
    }

    /**
     * Sets the value of the z4M2 property.
     * 
     */
    public void setZ4M2(float value) {
        this.z4M2 = value;
    }

    /**
     * Gets the value of the z40 property.
     * 
     */
    public float getZ40() {
        return z40;
    }

    /**
     * Sets the value of the z40 property.
     * 
     */
    public void setZ40(float value) {
        this.z40 = value;
    }

    /**
     * Gets the value of the z42 property.
     * 
     */
    public float getZ42() {
        return z42;
    }

    /**
     * Sets the value of the z42 property.
     * 
     */
    public void setZ42(float value) {
        this.z42 = value;
    }

    /**
     * Gets the value of the z44 property.
     * 
     */
    public float getZ44() {
        return z44;
    }

    /**
     * Sets the value of the z44 property.
     * 
     */
    public void setZ44(float value) {
        this.z44 = value;
    }

    /**
     * Gets the value of the z5M5 property.
     * 
     */
    public float getZ5M5() {
        return z5M5;
    }

    /**
     * Sets the value of the z5M5 property.
     * 
     */
    public void setZ5M5(float value) {
        this.z5M5 = value;
    }

    /**
     * Gets the value of the z5M3 property.
     * 
     */
    public float getZ5M3() {
        return z5M3;
    }

    /**
     * Sets the value of the z5M3 property.
     * 
     */
    public void setZ5M3(float value) {
        this.z5M3 = value;
    }

    /**
     * Gets the value of the z5M1 property.
     * 
     */
    public float getZ5M1() {
        return z5M1;
    }

    /**
     * Sets the value of the z5M1 property.
     * 
     */
    public void setZ5M1(float value) {
        this.z5M1 = value;
    }

    /**
     * Gets the value of the z51 property.
     * 
     */
    public float getZ51() {
        return z51;
    }

    /**
     * Sets the value of the z51 property.
     * 
     */
    public void setZ51(float value) {
        this.z51 = value;
    }

    /**
     * Gets the value of the z53 property.
     * 
     */
    public float getZ53() {
        return z53;
    }

    /**
     * Sets the value of the z53 property.
     * 
     */
    public void setZ53(float value) {
        this.z53 = value;
    }

    /**
     * Gets the value of the z55 property.
     * 
     */
    public float getZ55() {
        return z55;
    }

    /**
     * Sets the value of the z55 property.
     * 
     */
    public void setZ55(float value) {
        this.z55 = value;
    }

    /**
     * Gets the value of the z6M6 property.
     * 
     */
    public float getZ6M6() {
        return z6M6;
    }

    /**
     * Sets the value of the z6M6 property.
     * 
     */
    public void setZ6M6(float value) {
        this.z6M6 = value;
    }

    /**
     * Gets the value of the z6M4 property.
     * 
     */
    public float getZ6M4() {
        return z6M4;
    }

    /**
     * Sets the value of the z6M4 property.
     * 
     */
    public void setZ6M4(float value) {
        this.z6M4 = value;
    }

    /**
     * Gets the value of the z6M2 property.
     * 
     */
    public float getZ6M2() {
        return z6M2;
    }

    /**
     * Sets the value of the z6M2 property.
     * 
     */
    public void setZ6M2(float value) {
        this.z6M2 = value;
    }

    /**
     * Gets the value of the z60 property.
     * 
     */
    public float getZ60() {
        return z60;
    }

    /**
     * Sets the value of the z60 property.
     * 
     */
    public void setZ60(float value) {
        this.z60 = value;
    }

    /**
     * Gets the value of the z62 property.
     * 
     */
    public float getZ62() {
        return z62;
    }

    /**
     * Sets the value of the z62 property.
     * 
     */
    public void setZ62(float value) {
        this.z62 = value;
    }

    /**
     * Gets the value of the z64 property.
     * 
     */
    public float getZ64() {
        return z64;
    }

    /**
     * Sets the value of the z64 property.
     * 
     */
    public void setZ64(float value) {
        this.z64 = value;
    }

    /**
     * Gets the value of the z66 property.
     * 
     */
    public float getZ66() {
        return z66;
    }

    /**
     * Sets the value of the z66 property.
     * 
     */
    public void setZ66(float value) {
        this.z66 = value;
    }

    /**
     * Gets the value of the z7M7 property.
     * 
     */
    public float getZ7M7() {
        return z7M7;
    }

    /**
     * Sets the value of the z7M7 property.
     * 
     */
    public void setZ7M7(float value) {
        this.z7M7 = value;
    }

    /**
     * Gets the value of the z7M5 property.
     * 
     */
    public float getZ7M5() {
        return z7M5;
    }

    /**
     * Sets the value of the z7M5 property.
     * 
     */
    public void setZ7M5(float value) {
        this.z7M5 = value;
    }

    /**
     * Gets the value of the z7M3 property.
     * 
     */
    public float getZ7M3() {
        return z7M3;
    }

    /**
     * Sets the value of the z7M3 property.
     * 
     */
    public void setZ7M3(float value) {
        this.z7M3 = value;
    }

    /**
     * Gets the value of the z7M1 property.
     * 
     */
    public float getZ7M1() {
        return z7M1;
    }

    /**
     * Sets the value of the z7M1 property.
     * 
     */
    public void setZ7M1(float value) {
        this.z7M1 = value;
    }

    /**
     * Gets the value of the z71 property.
     * 
     */
    public float getZ71() {
        return z71;
    }

    /**
     * Sets the value of the z71 property.
     * 
     */
    public void setZ71(float value) {
        this.z71 = value;
    }

    /**
     * Gets the value of the z73 property.
     * 
     */
    public float getZ73() {
        return z73;
    }

    /**
     * Sets the value of the z73 property.
     * 
     */
    public void setZ73(float value) {
        this.z73 = value;
    }

    /**
     * Gets the value of the z75 property.
     * 
     */
    public float getZ75() {
        return z75;
    }

    /**
     * Sets the value of the z75 property.
     * 
     */
    public void setZ75(float value) {
        this.z75 = value;
    }

    /**
     * Gets the value of the z77 property.
     * 
     */
    public float getZ77() {
        return z77;
    }

    /**
     * Sets the value of the z77 property.
     * 
     */
    public void setZ77(float value) {
        this.z77 = value;
    }

}
