//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.19 at 07:48:00 PM CEST 
//


package essilor.integrator.adapter.domain.b2boptic;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Zernikes12 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Zernikes12">
 *   &lt;complexContent>
 *     &lt;extension base="{}Zernikes11">
 *       &lt;sequence>
 *         &lt;element name="z_12_M12" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="z_12_M10" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="z_12_M8" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="z_12_M6" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="z_12_M4" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="z_12_M2" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="z_12_0" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="z_12_2" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="z_12_4" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="z_12_6" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="z_12_8" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="z_12_10" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="z_12_12" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Zernikes12", propOrder = {
    "z12M12",
    "z12M10",
    "z12M8",
    "z12M6",
    "z12M4",
    "z12M2",
    "z120",
    "z122",
    "z124",
    "z126",
    "z128",
    "z1210",
    "z1212"
})
public class Zernikes12
    extends Zernikes11
{

    @XmlElement(name = "z_12_M12")
    protected float z12M12;
    @XmlElement(name = "z_12_M10")
    protected float z12M10;
    @XmlElement(name = "z_12_M8")
    protected float z12M8;
    @XmlElement(name = "z_12_M6")
    protected float z12M6;
    @XmlElement(name = "z_12_M4")
    protected float z12M4;
    @XmlElement(name = "z_12_M2")
    protected float z12M2;
    @XmlElement(name = "z_12_0")
    protected float z120;
    @XmlElement(name = "z_12_2")
    protected float z122;
    @XmlElement(name = "z_12_4")
    protected float z124;
    @XmlElement(name = "z_12_6")
    protected float z126;
    @XmlElement(name = "z_12_8")
    protected float z128;
    @XmlElement(name = "z_12_10")
    protected float z1210;
    @XmlElement(name = "z_12_12")
    protected float z1212;

    /**
     * Gets the value of the z12M12 property.
     * 
     */
    public float getZ12M12() {
        return z12M12;
    }

    /**
     * Sets the value of the z12M12 property.
     * 
     */
    public void setZ12M12(float value) {
        this.z12M12 = value;
    }

    /**
     * Gets the value of the z12M10 property.
     * 
     */
    public float getZ12M10() {
        return z12M10;
    }

    /**
     * Sets the value of the z12M10 property.
     * 
     */
    public void setZ12M10(float value) {
        this.z12M10 = value;
    }

    /**
     * Gets the value of the z12M8 property.
     * 
     */
    public float getZ12M8() {
        return z12M8;
    }

    /**
     * Sets the value of the z12M8 property.
     * 
     */
    public void setZ12M8(float value) {
        this.z12M8 = value;
    }

    /**
     * Gets the value of the z12M6 property.
     * 
     */
    public float getZ12M6() {
        return z12M6;
    }

    /**
     * Sets the value of the z12M6 property.
     * 
     */
    public void setZ12M6(float value) {
        this.z12M6 = value;
    }

    /**
     * Gets the value of the z12M4 property.
     * 
     */
    public float getZ12M4() {
        return z12M4;
    }

    /**
     * Sets the value of the z12M4 property.
     * 
     */
    public void setZ12M4(float value) {
        this.z12M4 = value;
    }

    /**
     * Gets the value of the z12M2 property.
     * 
     */
    public float getZ12M2() {
        return z12M2;
    }

    /**
     * Sets the value of the z12M2 property.
     * 
     */
    public void setZ12M2(float value) {
        this.z12M2 = value;
    }

    /**
     * Gets the value of the z120 property.
     * 
     */
    public float getZ120() {
        return z120;
    }

    /**
     * Sets the value of the z120 property.
     * 
     */
    public void setZ120(float value) {
        this.z120 = value;
    }

    /**
     * Gets the value of the z122 property.
     * 
     */
    public float getZ122() {
        return z122;
    }

    /**
     * Sets the value of the z122 property.
     * 
     */
    public void setZ122(float value) {
        this.z122 = value;
    }

    /**
     * Gets the value of the z124 property.
     * 
     */
    public float getZ124() {
        return z124;
    }

    /**
     * Sets the value of the z124 property.
     * 
     */
    public void setZ124(float value) {
        this.z124 = value;
    }

    /**
     * Gets the value of the z126 property.
     * 
     */
    public float getZ126() {
        return z126;
    }

    /**
     * Sets the value of the z126 property.
     * 
     */
    public void setZ126(float value) {
        this.z126 = value;
    }

    /**
     * Gets the value of the z128 property.
     * 
     */
    public float getZ128() {
        return z128;
    }

    /**
     * Sets the value of the z128 property.
     * 
     */
    public void setZ128(float value) {
        this.z128 = value;
    }

    /**
     * Gets the value of the z1210 property.
     * 
     */
    public float getZ1210() {
        return z1210;
    }

    /**
     * Sets the value of the z1210 property.
     * 
     */
    public void setZ1210(float value) {
        this.z1210 = value;
    }

    /**
     * Gets the value of the z1212 property.
     * 
     */
    public float getZ1212() {
        return z1212;
    }

    /**
     * Sets the value of the z1212 property.
     * 
     */
    public void setZ1212(float value) {
        this.z1212 = value;
    }

}
