//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.19 at 07:48:00 PM CEST 
//


package essilor.integrator.adapter.domain.b2boptic;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Zernikes9 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Zernikes9">
 *   &lt;complexContent>
 *     &lt;extension base="{}Zernikes8">
 *       &lt;sequence>
 *         &lt;element name="z_9_M9" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="z_9_M7" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="z_9_M5" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="z_9_M3" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="z_9_M1" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="z_9_1" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="z_9_3" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="z_9_5" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="z_9_7" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="z_9_9" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Zernikes9", propOrder = {
    "z9M9",
    "z9M7",
    "z9M5",
    "z9M3",
    "z9M1",
    "z91",
    "z93",
    "z95",
    "z97",
    "z99"
})
@XmlSeeAlso({
    Zernikes10 .class
})
public class Zernikes9
    extends Zernikes8
{

    @XmlElement(name = "z_9_M9")
    protected float z9M9;
    @XmlElement(name = "z_9_M7")
    protected float z9M7;
    @XmlElement(name = "z_9_M5")
    protected float z9M5;
    @XmlElement(name = "z_9_M3")
    protected float z9M3;
    @XmlElement(name = "z_9_M1")
    protected float z9M1;
    @XmlElement(name = "z_9_1")
    protected float z91;
    @XmlElement(name = "z_9_3")
    protected float z93;
    @XmlElement(name = "z_9_5")
    protected float z95;
    @XmlElement(name = "z_9_7")
    protected float z97;
    @XmlElement(name = "z_9_9")
    protected float z99;

    /**
     * Gets the value of the z9M9 property.
     * 
     */
    public float getZ9M9() {
        return z9M9;
    }

    /**
     * Sets the value of the z9M9 property.
     * 
     */
    public void setZ9M9(float value) {
        this.z9M9 = value;
    }

    /**
     * Gets the value of the z9M7 property.
     * 
     */
    public float getZ9M7() {
        return z9M7;
    }

    /**
     * Sets the value of the z9M7 property.
     * 
     */
    public void setZ9M7(float value) {
        this.z9M7 = value;
    }

    /**
     * Gets the value of the z9M5 property.
     * 
     */
    public float getZ9M5() {
        return z9M5;
    }

    /**
     * Sets the value of the z9M5 property.
     * 
     */
    public void setZ9M5(float value) {
        this.z9M5 = value;
    }

    /**
     * Gets the value of the z9M3 property.
     * 
     */
    public float getZ9M3() {
        return z9M3;
    }

    /**
     * Sets the value of the z9M3 property.
     * 
     */
    public void setZ9M3(float value) {
        this.z9M3 = value;
    }

    /**
     * Gets the value of the z9M1 property.
     * 
     */
    public float getZ9M1() {
        return z9M1;
    }

    /**
     * Sets the value of the z9M1 property.
     * 
     */
    public void setZ9M1(float value) {
        this.z9M1 = value;
    }

    /**
     * Gets the value of the z91 property.
     * 
     */
    public float getZ91() {
        return z91;
    }

    /**
     * Sets the value of the z91 property.
     * 
     */
    public void setZ91(float value) {
        this.z91 = value;
    }

    /**
     * Gets the value of the z93 property.
     * 
     */
    public float getZ93() {
        return z93;
    }

    /**
     * Sets the value of the z93 property.
     * 
     */
    public void setZ93(float value) {
        this.z93 = value;
    }

    /**
     * Gets the value of the z95 property.
     * 
     */
    public float getZ95() {
        return z95;
    }

    /**
     * Sets the value of the z95 property.
     * 
     */
    public void setZ95(float value) {
        this.z95 = value;
    }

    /**
     * Gets the value of the z97 property.
     * 
     */
    public float getZ97() {
        return z97;
    }

    /**
     * Sets the value of the z97 property.
     * 
     */
    public void setZ97(float value) {
        this.z97 = value;
    }

    /**
     * Gets the value of the z99 property.
     * 
     */
    public float getZ99() {
        return z99;
    }

    /**
     * Sets the value of the z99 property.
     * 
     */
    public void setZ99(float value) {
        this.z99 = value;
    }

}
