//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.19 at 07:48:00 PM CEST 
//


package essilor.integrator.adapter.domain.b2boptic;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Zernikes8 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Zernikes8">
 *   &lt;complexContent>
 *     &lt;extension base="{}Zernikes7">
 *       &lt;sequence>
 *         &lt;element name="z_8_M8" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="z_8_M6" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="z_8_M4" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="z_8_M2" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="z_8_0" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="z_8_2" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="z_8_4" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="z_8_6" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="z_8_8" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Zernikes8", propOrder = {
    "z8M8",
    "z8M6",
    "z8M4",
    "z8M2",
    "z80",
    "z82",
    "z84",
    "z86",
    "z88"
})
@XmlSeeAlso({
    Zernikes9 .class
})
public class Zernikes8
    extends Zernikes7
{

    @XmlElement(name = "z_8_M8")
    protected float z8M8;
    @XmlElement(name = "z_8_M6")
    protected float z8M6;
    @XmlElement(name = "z_8_M4")
    protected float z8M4;
    @XmlElement(name = "z_8_M2")
    protected float z8M2;
    @XmlElement(name = "z_8_0")
    protected float z80;
    @XmlElement(name = "z_8_2")
    protected float z82;
    @XmlElement(name = "z_8_4")
    protected float z84;
    @XmlElement(name = "z_8_6")
    protected float z86;
    @XmlElement(name = "z_8_8")
    protected float z88;

    /**
     * Gets the value of the z8M8 property.
     * 
     */
    public float getZ8M8() {
        return z8M8;
    }

    /**
     * Sets the value of the z8M8 property.
     * 
     */
    public void setZ8M8(float value) {
        this.z8M8 = value;
    }

    /**
     * Gets the value of the z8M6 property.
     * 
     */
    public float getZ8M6() {
        return z8M6;
    }

    /**
     * Sets the value of the z8M6 property.
     * 
     */
    public void setZ8M6(float value) {
        this.z8M6 = value;
    }

    /**
     * Gets the value of the z8M4 property.
     * 
     */
    public float getZ8M4() {
        return z8M4;
    }

    /**
     * Sets the value of the z8M4 property.
     * 
     */
    public void setZ8M4(float value) {
        this.z8M4 = value;
    }

    /**
     * Gets the value of the z8M2 property.
     * 
     */
    public float getZ8M2() {
        return z8M2;
    }

    /**
     * Sets the value of the z8M2 property.
     * 
     */
    public void setZ8M2(float value) {
        this.z8M2 = value;
    }

    /**
     * Gets the value of the z80 property.
     * 
     */
    public float getZ80() {
        return z80;
    }

    /**
     * Sets the value of the z80 property.
     * 
     */
    public void setZ80(float value) {
        this.z80 = value;
    }

    /**
     * Gets the value of the z82 property.
     * 
     */
    public float getZ82() {
        return z82;
    }

    /**
     * Sets the value of the z82 property.
     * 
     */
    public void setZ82(float value) {
        this.z82 = value;
    }

    /**
     * Gets the value of the z84 property.
     * 
     */
    public float getZ84() {
        return z84;
    }

    /**
     * Sets the value of the z84 property.
     * 
     */
    public void setZ84(float value) {
        this.z84 = value;
    }

    /**
     * Gets the value of the z86 property.
     * 
     */
    public float getZ86() {
        return z86;
    }

    /**
     * Sets the value of the z86 property.
     * 
     */
    public void setZ86(float value) {
        this.z86 = value;
    }

    /**
     * Gets the value of the z88 property.
     * 
     */
    public float getZ88() {
        return z88;
    }

    /**
     * Sets the value of the z88 property.
     * 
     */
    public void setZ88(float value) {
        this.z88 = value;
    }

}
