//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.03 at 09:48:44 PM CEST 
//


package essilor.integrator.adapter.domain.uploadfile;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the essilor.integrator.adapter.domain.uploadfile package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: essilor.integrator.adapter.domain.uploadfile
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link UploadFileUserResponse }
     * 
     */
    public UploadFileUserResponse createUploadFileUserResponse() {
        return new UploadFileUserResponse();
    }

    /**
     * Create an instance of {@link UploadOrderByActionWithWarningManagement }
     * 
     */
    public UploadOrderByActionWithWarningManagement createUploadOrderByActionWithWarningManagement() {
        return new UploadOrderByActionWithWarningManagement();
    }

    /**
     * Create an instance of {@link Trace }
     * 
     */
    public Trace createTrace() {
        return new Trace();
    }

    /**
     * Create an instance of {@link ArrayOfString }
     * 
     */
    public ArrayOfString createArrayOfString() {
        return new ArrayOfString();
    }

    /**
     * Create an instance of {@link UploadOrderByActionWarningsAccepted }
     * 
     */
    public UploadOrderByActionWarningsAccepted createUploadOrderByActionWarningsAccepted() {
        return new UploadOrderByActionWarningsAccepted();
    }

    /**
     * Create an instance of {@link UploadOrderByActionResponse }
     * 
     */
    public UploadOrderByActionResponse createUploadOrderByActionResponse() {
        return new UploadOrderByActionResponse();
    }

    /**
     * Create an instance of {@link ResponseInfo }
     * 
     */
    public ResponseInfo createResponseInfo() {
        return new ResponseInfo();
    }

    /**
     * Create an instance of {@link UploadFileUser }
     * 
     */
    public UploadFileUser createUploadFileUser() {
        return new UploadFileUser();
    }

    /**
     * Create an instance of {@link SendOrderResponse }
     * 
     */
    public SendOrderResponse createSendOrderResponse() {
        return new SendOrderResponse();
    }

    /**
     * Create an instance of {@link Response }
     * 
     */
    public Response createResponse() {
        return new Response();
    }

    /**
     * Create an instance of {@link UploadOrderByActionWarningsAcceptedResponse }
     * 
     */
    public UploadOrderByActionWarningsAcceptedResponse createUploadOrderByActionWarningsAcceptedResponse() {
        return new UploadOrderByActionWarningsAcceptedResponse();
    }

    /**
     * Create an instance of {@link UploadOrderByAction }
     * 
     */
    public UploadOrderByAction createUploadOrderByAction() {
        return new UploadOrderByAction();
    }

    /**
     * Create an instance of {@link UploadCustomFile }
     * 
     */
    public UploadCustomFile createUploadCustomFile() {
        return new UploadCustomFile();
    }

    /**
     * Create an instance of {@link SendOrder }
     * 
     */
    public SendOrder createSendOrder() {
        return new SendOrder();
    }

    /**
     * Create an instance of {@link UploadCustomFileResponse }
     * 
     */
    public UploadCustomFileResponse createUploadCustomFileResponse() {
        return new UploadCustomFileResponse();
    }

    /**
     * Create an instance of {@link CustomFileInfo }
     * 
     */
    public CustomFileInfo createCustomFileInfo() {
        return new CustomFileInfo();
    }

    /**
     * Create an instance of {@link UploadCustomFileActionResponse }
     * 
     */
    public UploadCustomFileActionResponse createUploadCustomFileActionResponse() {
        return new UploadCustomFileActionResponse();
    }

    /**
     * Create an instance of {@link UploadOrderByActionWithWarningManagementResponse }
     * 
     */
    public UploadOrderByActionWithWarningManagementResponse createUploadOrderByActionWithWarningManagementResponse() {
        return new UploadOrderByActionWithWarningManagementResponse();
    }

    /**
     * Create an instance of {@link UploadFile }
     * 
     */
    public UploadFile createUploadFile() {
        return new UploadFile();
    }

    /**
     * Create an instance of {@link UploadCustomFileAction }
     * 
     */
    public UploadCustomFileAction createUploadCustomFileAction() {
        return new UploadCustomFileAction();
    }

    /**
     * Create an instance of {@link UploadFileResponse }
     * 
     */
    public UploadFileResponse createUploadFileResponse() {
        return new UploadFileResponse();
    }

    /**
     * Create an instance of {@link Calculation }
     * 
     */
    public Calculation createCalculation() {
        return new Calculation();
    }

    /**
     * Create an instance of {@link ArrayOfOrderError }
     * 
     */
    public ArrayOfOrderError createArrayOfOrderError() {
        return new ArrayOfOrderError();
    }

    /**
     * Create an instance of {@link CalculationResults }
     * 
     */
    public CalculationResults createCalculationResults() {
        return new CalculationResults();
    }

    /**
     * Create an instance of {@link OrderError }
     * 
     */
    public OrderError createOrderError() {
        return new OrderError();
    }

}
