//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.03 at 09:48:44 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://services.visionweb.com", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package essilor.integrator.adapter.domain.uploadfile;
