//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.03 at 09:48:44 PM CEST 
//


package essilor.integrator.adapter.domain.uploadfile;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="username" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="pswd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="filestring" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="subordid" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="refid" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="guid" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="msgguid" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="sloid" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="cbsid" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ordtype" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="filename" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "username",
    "pswd",
    "filestring",
    "subordid",
    "refid",
    "guid",
    "msgguid",
    "sloid",
    "cbsid",
    "ordtype",
    "filename"
})
@XmlRootElement(name = "UploadFile")
public class UploadFile {

    protected String username;
    protected String pswd;
    protected String filestring;
    protected String subordid;
    protected String refid;
    protected String guid;
    protected String msgguid;
    protected String sloid;
    protected String cbsid;
    protected String ordtype;
    protected String filename;

    /**
     * Gets the value of the username property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUsername() {
        return username;
    }

    /**
     * Sets the value of the username property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUsername(String value) {
        this.username = value;
    }

    /**
     * Gets the value of the pswd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPswd() {
        return pswd;
    }

    /**
     * Sets the value of the pswd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPswd(String value) {
        this.pswd = value;
    }

    /**
     * Gets the value of the filestring property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFilestring() {
        return filestring;
    }

    /**
     * Sets the value of the filestring property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFilestring(String value) {
        this.filestring = value;
    }

    /**
     * Gets the value of the subordid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubordid() {
        return subordid;
    }

    /**
     * Sets the value of the subordid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubordid(String value) {
        this.subordid = value;
    }

    /**
     * Gets the value of the refid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRefid() {
        return refid;
    }

    /**
     * Sets the value of the refid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRefid(String value) {
        this.refid = value;
    }

    /**
     * Gets the value of the guid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGuid() {
        return guid;
    }

    /**
     * Sets the value of the guid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGuid(String value) {
        this.guid = value;
    }

    /**
     * Gets the value of the msgguid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMsgguid() {
        return msgguid;
    }

    /**
     * Sets the value of the msgguid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMsgguid(String value) {
        this.msgguid = value;
    }

    /**
     * Gets the value of the sloid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSloid() {
        return sloid;
    }

    /**
     * Sets the value of the sloid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSloid(String value) {
        this.sloid = value;
    }

    /**
     * Gets the value of the cbsid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCbsid() {
        return cbsid;
    }

    /**
     * Sets the value of the cbsid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCbsid(String value) {
        this.cbsid = value;
    }

    /**
     * Gets the value of the ordtype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrdtype() {
        return ordtype;
    }

    /**
     * Sets the value of the ordtype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrdtype(String value) {
        this.ordtype = value;
    }

    /**
     * Gets the value of the filename property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFilename() {
        return filename;
    }

    /**
     * Sets the value of the filename property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFilename(String value) {
        this.filename = value;
    }

}
