//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.03 at 09:48:44 PM CEST 
//


package essilor.integrator.adapter.domain.uploadfile;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="UploadOrderByActionWarningsAcceptedResult" type="{http://services.visionweb.com}ResponseInfo" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "uploadOrderByActionWarningsAcceptedResult"
})
@XmlRootElement(name = "UploadOrderByActionWarningsAcceptedResponse")
public class UploadOrderByActionWarningsAcceptedResponse {

    @XmlElement(name = "UploadOrderByActionWarningsAcceptedResult")
    protected ResponseInfo uploadOrderByActionWarningsAcceptedResult;

    /**
     * Gets the value of the uploadOrderByActionWarningsAcceptedResult property.
     * 
     * @return
     *     possible object is
     *     {@link ResponseInfo }
     *     
     */
    public ResponseInfo getUploadOrderByActionWarningsAcceptedResult() {
        return uploadOrderByActionWarningsAcceptedResult;
    }

    /**
     * Sets the value of the uploadOrderByActionWarningsAcceptedResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResponseInfo }
     *     
     */
    public void setUploadOrderByActionWarningsAcceptedResult(ResponseInfo value) {
        this.uploadOrderByActionWarningsAcceptedResult = value;
    }

}
