//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.03 at 09:46:51 PM CEST 
//


package essilor.integrator.adapter.domain.owvalidation;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the essilor.integrator.adapter.domain.owvalidation package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: essilor.integrator.adapter.domain.owvalidation
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ValidateQuotationResponse }
     * 
     */
    public ValidateQuotationResponse createValidateQuotationResponse() {
        return new ValidateQuotationResponse();
    }

    /**
     * Create an instance of {@link QuotationResults }
     * 
     */
    public QuotationResults createQuotationResults() {
        return new QuotationResults();
    }

    /**
     * Create an instance of {@link ValidateQuotation }
     * 
     */
    public ValidateQuotation createValidateQuotation() {
        return new ValidateQuotation();
    }

    /**
     * Create an instance of {@link ValidateOrderFromOrderXml }
     * 
     */
    public ValidateOrderFromOrderXml createValidateOrderFromOrderXml() {
        return new ValidateOrderFromOrderXml();
    }

    /**
     * Create an instance of {@link VWLoginInfo }
     * 
     */
    public VWLoginInfo createVWLoginInfo() {
        return new VWLoginInfo();
    }

    /**
     * Create an instance of {@link ValidateOrderFromPMS }
     * 
     */
    public ValidateOrderFromPMS createValidateOrderFromPMS() {
        return new ValidateOrderFromPMS();
    }

    /**
     * Create an instance of {@link ValidateOrderFromPMSResponse }
     * 
     */
    public ValidateOrderFromPMSResponse createValidateOrderFromPMSResponse() {
        return new ValidateOrderFromPMSResponse();
    }

    /**
     * Create an instance of {@link ArrayOfOrderError }
     * 
     */
    public ArrayOfOrderError createArrayOfOrderError() {
        return new ArrayOfOrderError();
    }

    /**
     * Create an instance of {@link ValidateOrderFromOrderXmlResponse }
     * 
     */
    public ValidateOrderFromOrderXmlResponse createValidateOrderFromOrderXmlResponse() {
        return new ValidateOrderFromOrderXmlResponse();
    }

    /**
     * Create an instance of {@link ArrayOfErrorMessage }
     * 
     */
    public ArrayOfErrorMessage createArrayOfErrorMessage() {
        return new ArrayOfErrorMessage();
    }

    /**
     * Create an instance of {@link ErrorMessage }
     * 
     */
    public ErrorMessage createErrorMessage() {
        return new ErrorMessage();
    }

    /**
     * Create an instance of {@link Calculation }
     * 
     */
    public Calculation createCalculation() {
        return new Calculation();
    }

    /**
     * Create an instance of {@link CalculationResults }
     * 
     */
    public CalculationResults createCalculationResults() {
        return new CalculationResults();
    }

    /**
     * Create an instance of {@link OrderError }
     * 
     */
    public OrderError createOrderError() {
        return new OrderError();
    }

}
