//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.03 at 09:46:51 PM CEST 
//


package essilor.integrator.adapter.domain.owvalidation;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for QuotationResults complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="QuotationResults">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Calculation" type="{http://OpsysWeb.eu/}CalculationResults" minOccurs="0"/>
 *         &lt;element name="Errors" type="{http://OpsysWeb.eu/}ArrayOfOrderError" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "QuotationResults", propOrder = {
    "calculation",
    "errors"
})
public class QuotationResults {

    @XmlElement(name = "Calculation")
    protected CalculationResults calculation;
    @XmlElement(name = "Errors")
    protected ArrayOfOrderError errors;

    /**
     * Gets the value of the calculation property.
     * 
     * @return
     *     possible object is
     *     {@link CalculationResults }
     *     
     */
    public CalculationResults getCalculation() {
        return calculation;
    }

    /**
     * Sets the value of the calculation property.
     * 
     * @param value
     *     allowed object is
     *     {@link CalculationResults }
     *     
     */
    public void setCalculation(CalculationResults value) {
        this.calculation = value;
    }

    /**
     * Gets the value of the errors property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfOrderError }
     *     
     */
    public ArrayOfOrderError getErrors() {
        return errors;
    }

    /**
     * Sets the value of the errors property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfOrderError }
     *     
     */
    public void setErrors(ArrayOfOrderError value) {
        this.errors = value;
    }

}
