//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.03 at 09:48:07 PM CEST 
//


package essilor.integrator.adapter.domain.getorder;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the essilor.integrator.adapter.domain.getorder package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: essilor.integrator.adapter.domain.getorder
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetOrderObjectByPoNum }
     * 
     */
    public GetOrderObjectByPoNum createGetOrderObjectByPoNum() {
        return new GetOrderObjectByPoNum();
    }

    /**
     * Create an instance of {@link GetOrderByPoNum }
     * 
     */
    public GetOrderByPoNum createGetOrderByPoNum() {
        return new GetOrderByPoNum();
    }

    /**
     * Create an instance of {@link GetOrderByPoNumTimestamp }
     * 
     */
    public GetOrderByPoNumTimestamp createGetOrderByPoNumTimestamp() {
        return new GetOrderByPoNumTimestamp();
    }

    /**
     * Create an instance of {@link GetOrderAsPDFResponse }
     * 
     */
    public GetOrderAsPDFResponse createGetOrderAsPDFResponse() {
        return new GetOrderAsPDFResponse();
    }

    /**
     * Create an instance of {@link OrderPdf }
     * 
     */
    public OrderPdf createOrderPdf() {
        return new OrderPdf();
    }

    /**
     * Create an instance of {@link GetOrderByPoNumResponse }
     * 
     */
    public GetOrderByPoNumResponse createGetOrderByPoNumResponse() {
        return new GetOrderByPoNumResponse();
    }

    /**
     * Create an instance of {@link GetOrderObjectByPoNumResponse }
     * 
     */
    public GetOrderObjectByPoNumResponse createGetOrderObjectByPoNumResponse() {
        return new GetOrderObjectByPoNumResponse();
    }

    /**
     * Create an instance of {@link OrderXml }
     * 
     */
    public OrderXml createOrderXml() {
        return new OrderXml();
    }

    /**
     * Create an instance of {@link GetOrderCompressedResponse }
     * 
     */
    public GetOrderCompressedResponse createGetOrderCompressedResponse() {
        return new GetOrderCompressedResponse();
    }

    /**
     * Create an instance of {@link GetOrderListResponse }
     * 
     */
    public GetOrderListResponse createGetOrderListResponse() {
        return new GetOrderListResponse();
    }

    /**
     * Create an instance of {@link GetOrderResponse }
     * 
     */
    public GetOrderResponse createGetOrderResponse() {
        return new GetOrderResponse();
    }

    /**
     * Create an instance of {@link GetOrderAsPDFByPoNumResponse }
     * 
     */
    public GetOrderAsPDFByPoNumResponse createGetOrderAsPDFByPoNumResponse() {
        return new GetOrderAsPDFByPoNumResponse();
    }

    /**
     * Create an instance of {@link GetOrderByPoNumTimestampResponse }
     * 
     */
    public GetOrderByPoNumTimestampResponse createGetOrderByPoNumTimestampResponse() {
        return new GetOrderByPoNumTimestampResponse();
    }

    /**
     * Create an instance of {@link GetOrder }
     * 
     */
    public GetOrder createGetOrder() {
        return new GetOrder();
    }

    /**
     * Create an instance of {@link GetOrderList }
     * 
     */
    public GetOrderList createGetOrderList() {
        return new GetOrderList();
    }

    /**
     * Create an instance of {@link GetOrderAsPDFByPoNum }
     * 
     */
    public GetOrderAsPDFByPoNum createGetOrderAsPDFByPoNum() {
        return new GetOrderAsPDFByPoNum();
    }

    /**
     * Create an instance of {@link GetOrderAsPDF }
     * 
     */
    public GetOrderAsPDF createGetOrderAsPDF() {
        return new GetOrderAsPDF();
    }

    /**
     * Create an instance of {@link GetOrderObjectByPoNumTimestampResponse }
     * 
     */
    public GetOrderObjectByPoNumTimestampResponse createGetOrderObjectByPoNumTimestampResponse() {
        return new GetOrderObjectByPoNumTimestampResponse();
    }

    /**
     * Create an instance of {@link GetOrderCompressed }
     * 
     */
    public GetOrderCompressed createGetOrderCompressed() {
        return new GetOrderCompressed();
    }

    /**
     * Create an instance of {@link GetOrderObjectByPoNumTimestamp }
     * 
     */
    public GetOrderObjectByPoNumTimestamp createGetOrderObjectByPoNumTimestamp() {
        return new GetOrderObjectByPoNumTimestamp();
    }

}
